- bin/langstream
* When using the cli, it must point to the `conf/cli.yaml` as expected. Instead currently it points to the target directory which is not handy for the user
> Cli: default config must point to conf/cli.yaml

- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/InfiniteRetry.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/agents/AgentController.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/apps/AppController.java
* Currently the deployer uses the default retry config. This retry config is applied when the reconciliation loop fails. The correct behaviour would to be retry forever until the patch is in the requested state otherwise it seems everything is fine even if it's not able to update the resources for some reasons.
> Deployer: set infinite retries

- examples/applications/query-pinecone/README.md
- examples/applications/query-pinecone/query.yaml
- examples/applications/query-pinecone/wite.yaml
- examples/applications/query-pinecone/write.yaml
- langstream-agents/langstream-ai-agents/pom.xml
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/datasource/DataSourceProviderRegistry.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/datasource/impl/AstraDataSource.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/datasource/impl/JdbcDataSourceProvider.java
- langstream-agents/langstream-ai-agents/src/test/java/ai/langstream/ai/agents/datasource/JdbcDataSourceProviderTest.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/VectorAgentsCodeProvider.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/VectorDBSinkAgent.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/datasource/impl/PineconeConfig.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/datasource/impl/PineconeWriter.java
- langstream-agents/langstream-vector-agents/src/main/resources/META-INF/services/ai.langstream.api.database.VectorDatabaseWriterProvider
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/PineconeDataSourceTest.java
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/PineconeWriterTest.java
- langstream-api/src/main/java/ai/langstream/api/database/VectorDatabaseWriter.java
- langstream-api/src/main/java/ai/langstream/api/database/VectorDatabaseWriterProvider.java
- langstream-api/src/main/java/ai/langstream/api/database/VectorDatabaseWriterProviderRegistry.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/QueryVectorDBAgentProvider.java
- langstream-pulsar/pom.xml
- pom.xml
Summary:
- introduce a new "vector-db-sink" agent, that is able to write to "Vector databases"
- introduce the first implementation for Pinecone
- the examples/applications/query-pinecone application now both writes and reads from Pinecone
- the syntax for the mapping is the same as for the "compute" step (based on the JSTL Expression Language)
In Pinecone a Vector has an id, a vector and a bunch of metadata (please refer to the Pinecone docs).
In the Sink you can declare how those fields are computed.
The syntax depends on the Vector DB, as each Vector DB has its own model.
Sample pipeline:
```
name: "Index Products on Vector Database"
topics:
- name: "vectors-topic"
errors:
on-failure: skip
pipeline:
- name: "compute-embeddings"
id: "step1"
type: …
```
> Vector Database Support: vector-db-sink agent + support for Pinecone

- langstream-api/src/main/java/ai/langstream/api/codestorage/DownloadedCodeArchive.java
- langstream-api/src/main/java/ai/langstream/api/codestorage/GenericZipFileArchiveFile.java
- langstream-api/src/main/java/ai/langstream/api/codestorage/LocalZipFileArchiveFile.java
- langstream-cli/src/main/java/ai/langstream/cli/client/LangStreamClient.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootAppCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/DownloadApplicationCodeCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/AppsCmdTest.java
- langstream-codestorage-s3/src/main/java/ai/langstream/impl/storage/k8s/codestorage/S3CodeStorage.java
- langstream-core/src/main/java/ai/langstream/impl/codestorage/NoopCodeStorageProvider.java
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationResource.java
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationService.java
- langstream-webservice/src/main/java/ai/langstream/webservice/application/CodeStorageService.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/ApplicationResourceTest.java
* New GET endpoints `/api/applications/{tenant}/{app}/code` and  `/api/applications/{tenant}/{app}/code/{codeArchiveRef}` to download the code from s3. Note that the latter one will be used only internal since the ID is not retrievable from the base user. In any case the ref must own to that application and tenant.
* New CLI command `langstream apps download myapp -o /myfile.zip` or `langstream apps download myapp`
> Control plane/CLI: add endpoint to download application's code

- examples/applications/query-jdbc/configuration.yaml
- langstream-agents/langstream-agent-s3/pom.xml
- langstream-agents/langstream-agent-s3/src/test/java/ai/langstream/agents/s3/S3SourceTest.java
- langstream-agents/langstream-agent-webcrawler/pom.xml
- langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/WebCrawlerSourceTest.java
- langstream-agents/langstream-agents-text-processing/pom.xml
- langstream-agents/langstream-ai-agents/pom.xml
- langstream-agents/langstream-vector-agents/pom.xml
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/PineconeWriterTest.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentCodeAndLoader.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentCodeRegistry.java
- langstream-runtime/langstream-runtime-impl/pom.xml
- langstream-runtime/langstream-runtime-impl/src/main/assemble/langstream-runtime.xml
- langstream-runtime/langstream-runtime-impl/src/main/docker/Dockerfile
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/CompositeAgentProcessor.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/api/AgentInfo.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/nar/NarFileHandler.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/ComputeEmbeddingsIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/GenIAgentsRunnerIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/KafkaConnectSinkRunnerIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/KafkaConnectSourceRunnerIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/LoadAgentCodeIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/LoadAgentCodeTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/QueryVectorDBIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/TextProcessingAgentsRunnerIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/pulsar/PulsarRunnerDockerTest.java
- pom.xml
Summary:
- in order to prevent classpath pollution we have to package each system agent into a self-contained bundle
- at runtime we load each agent from their own package
> Package system agents with isolated classpath (using NiFi Nar)

- langstream-agents/langstream-agent-s3/src/main/resources/META-INF/ai.langstream.agents.index
- langstream-agents/langstream-agent-webcrawler/src/main/resources/META-INF/ai.langstream.agents.index
- langstream-agents/langstream-agents-text-processing/src/main/resources/META-INF/ai.langstream.agents.index
- langstream-agents/langstream-ai-agents/src/main/resources/META-INF/ai.langstream.agents.index
- langstream-agents/langstream-vector-agents/src/main/resources/META-INF/ai.langstream.agents.index
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentCodeRegistry.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/nar/NarFileHandler.java
Summary:
- allow to add a META-INF/ai.langstream.agents.index file that contains a static list of agent types that are handled by the package
- when looking for the AgentCode given an agent-type, load only the package that contains the agent, fall back to looking into all the packages in case the agent is not found
Follow up:
should we forbid to not have the static index ?
after all we have full control of the .nar files and if a .nar file has no static index then it is not built by us.
Unfortunately this index file conflicts with the dynamic AgentCodeProvider way based on ServiceLoader, that is more powerful.
> AgentCodeRegistry/NarFileHandler: do not unpack unecessary nar files

- langstream-admin-client/pom.xml
- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClientConfiguration.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClientLogger.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/model/Applications.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/util/MultiPartBodyPublisher.java
- langstream-cli/pom.xml
- langstream-cli/src/main/java/ai/langstream/cli/commands/BaseCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/GetApplicationLogsCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/configure/ConfigureCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/BaseGatewayCmd.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentCodeDownloader.java
- pom.xml
This basically split the CLI code and the actual http client for the control plane. 
For now only applications are implemented. 
This is a preparatory work for moving the code download to use the new endpoint instead of s3 directly
> Create Java Admin client module

- langstream-runtime/langstream-runtime-impl/src/main/python/Pipfile.lock
This updates llama_index to 0.8.8 which has support for cassio.
> Bump python runtime deps (llama_index to 0.8.8)

- bin/get-cli.sh
- langstream-e2e-tests/src/test/java/ai/langstream/tests/BaseEndToEndTest.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/CassandraSinkIT.java
- langstream-k8s-deployer/langstream-k8s-deployer-api/src/main/java/ai/langstream/deployer/k8s/api/crds/apps/ApplicationSpec.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/apps/AppResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/apps/AppResourcesFactoryTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/apps/ApplicationCustomResourceTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/DeployerConfiguration.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/ResolvedDeployerConfiguration.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/apps/AppController.java
- langstream-k8s-storage/src/main/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStore.java
- langstream-k8s-storage/src/main/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStoreProperties.java
- langstream-k8s-storage/src/test/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStoreLogsTest.java
- langstream-k8s-storage/src/test/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStoreTest.java
- langstream-webservice/src/main/resources/application.properties
The application custom resource contains the runtime image to use. The runtime image version is decided by the control plane. 
The compatibility between deployer and runtime image is guaranteed across the same version. Since the CR contains the image, the deployer jobs (setup and cleanup) images are not controlled by the deployer. This becomes a big problem since there could be very old images used at any time (with the latest version of the deployer).
* Deprecated the image and imagePullPolicy fields in the application custom resource
* Removed the configuration for the runtime images in the control plane
* Added configuration for runtime images in the deployer.
* Still support old behaviour to guarantee backward compatibility in case the deployer doesn't have the runtime image …
> Runtime images should be always in-sync with the deployer config

- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
This way users can install target libs to their `python/lib` dir.
When they run locally they shouldn't have `python/lib` on their python path so the libs won't be used.
> Add /app-code-download/python/lib to the PYTHONPATH

- langstream-cli/src/main/java/ai/langstream/cli/websocket/WebSocketClient.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/PythonFunctionIT.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/apps/AppResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactoryTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/apps/AppResourcesFactoryTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/AgentControllerIT.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/AppControllerIT.java
- langstream-runtime/langstream-runtime-api/src/main/java/ai/langstream/runtime/api/agent/AgentRunnerConstants.java
- langstream-runtime/langstream-runtime-api/src/main/java/ai/langstream/runtime/api/deployer/RuntimeDeployerConstants.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/Main.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentCodeDownloader.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunnerStarter.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/deployer/RuntimeDeployer.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/deployer/RuntimeDeployerStarter.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/pulsar/PulsarRunnerDockerTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/agent/AgentRunnerStarterTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/deployer/RuntimeDeployerStarterTest.java
In order to guarantee compatibility when adding/removing arguments in the runtime pods (both deployer and agent) it's better to not use positional arguments which may leads to inverted parameters and unexpected behaviours. 
* For each property, reads the env first. If not found, use the arg as it was before
* Deployer now only uses env
Old deployer will still generate args so the new runtime pod is still compatible
> Move runtime pods from args to env

- examples/applications/webcrawler-source/crawler.yaml
- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/WebCrawlerSource.java
- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawler.java
- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerConfiguration.java
- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerStatus.java
- langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/WebCrawlerSourceTest.java
- langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerConfigurationTest.java
- langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerTest.java
- langstream-api/src/main/java/ai/langstream/api/util/ConfigurationUtils.java
- langstream-kafka/src/main/java/ai/langstream/kafka/runner/KafkaProducerWrapper.java
Summary:
- handle redirections
- handle permanent failures (skip the document, forever)
- handle temporary failures (put back the document into the backlog, retry N times)
- handle cookies
- handle timeout
- allowed-domains: now this is a list of "domains" and "url prefixes" (for compatibility reasons) 
Full example:
```
pipeline:
- name: "Crawl the WebSite"
type: "webcrawler-source"
configuration:
seed-urls: "https://docs.langstream.ai/"
allowed-domains: "docs.langstream.ai"
min-time-between-requests: 100
max-error-count: 5
http-timeout: 10000
handle-cookies: true
max-unflushed-pages: 100
user-agent: "langstream.ai-webcrawler/1.0"
bucketName: "{{{secrets.s3-credentials.bucket-name}}}"
endpoint: "{{{secrets.s3-credentials.endpoint}}}"
access-key: "{{{secrets.s3-credentials.access-key}}}" …
```
> WebCrawler: improvements

- langstream-e2e-tests/src/test/java/ai/langstream/tests/BaseEndToEndTest.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/PythonFunctionIT.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/apps/AppResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactoryTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/apps/AppResourcesFactoryTest.java
- langstream-webservice/src/main/docker/jib/entrypoint.sh
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationResource.java
- langstream-webservice/src/main/java/ai/langstream/webservice/security/infrastructure/primary/JwksUriSigningKeyResolver.java
- langstream-webservice/src/main/java/ai/langstream/webservice/security/infrastructure/primary/LocalKubernetesJwksUriSigningKeyResolver.java
- langstream-webservice/src/test/java/ai/langstream/webservice/security/infrastructure/primary/SecurityConfigurationTest.java
* Added support for oidc issuer that doesn't resolve to local kubernetes dns
* Fixed certificate import at control plane startup to also load system certs
* Fixed authz check for admin accessing tenant's applications endpoints
* Added support for OIDC providers that exposes multiple keys (before we were getting the first one instead of the one in the jwt header)
* Agent runtime wasn't using the service account of that tenant, therefore it was authenticating to the control plane with the role "default" - my testing was done using the "default" tenant 😞
> Fixes using OIDC on AWS

- .github/workflows/release-python.yml
The `-am` flag is not enough as NAR files are needed.
To unblock, we install the full project for now.
In the future we should find a way to just have to build the python part.
> Fix python release action

- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/PodTemplate.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/apps/AppResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactoryTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/apps/AppResourcesFactoryTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/DeployerConfiguration.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/ResolvedDeployerConfiguration.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/agents/AgentController.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/apps/AppController.java
* Added new option in the deployer configmap under podTemplate.annotations
* Added new options for specifying annotations only for the app deployer vs agent runner. If not configured, they fallback to `podTemplate`.
So you can configure annotations in this way:
```
deployer:
app:
config: 
podTemplate:
annotations: 
my-ann: value1
```
or only for the agent runner
```
deployer:
app:
config: 
agentPodTemplate:
annotations: 
my-ann: value1
```
or only for the app deployer
```
deployer:
app:
config: 
appDeployerPodTemplate:
annotations: 
my-ann: value1
```
> Add option to configure additional runtime pod annotations

- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/GenAIToolKitAgent.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentProcessor.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/SingleRecordAgentProcessor.java
- langstream-api/src/main/java/ai/langstream/api/util/ConfigurationUtils.java
- langstream-core/src/main/java/ai/langstream/impl/common/BasicClusterRuntime.java
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
- langstream-kafka/src/main/java/ai/langstream/kafka/runner/KafkaConsumerWrapper.java
- langstream-kafka/src/main/java/ai/langstream/kafka/runtime/KafkaTopic.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunnerStarter.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/CompositeAgentProcessor.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/TopicConsumerSource.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/AsyncProcessingIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/ErrorHandlingTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/mockagents/MockProcessorAgentsCodeProvider.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/mockagents/MockProcessorAgentsProvider.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/pulsar/PulsarRunnerDockerTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/agent/AgentRunnerStarterTest.java
Summary:
- ensure that we are properly committing the offsets in case of all the types of failure handling
- add tests with async processors
- add some validations in the model parser in order to have better errors in some cases
- reports on the TopicSource the status of the consumer: current committed offsets and current uncommitted offsets (due to out of order processing)
- fix a bug in CompositeAgent in presence of agents that generate more messages from a single message (like the TextSplitterAgent)
> Add integration tests and harden failure handling in Java code

- langstream-agents/langstream-agents-text-processing/src/main/java/ai/langstream/agents/text/DocumentToJsonAgent.java
- langstream-agents/langstream-agents-text-processing/src/main/java/ai/langstream/agents/text/TikaTextExtractorAgent.java
- langstream-agents/langstream-agents-text-processing/src/test/java/ai/langstream/agents/text/DocumentToJsonTest.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/SimpleRecord.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunnerStarter.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/TextProcessingAgentsRunnerIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/pulsar/PulsarRunnerDockerTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/agent/AgentRunnerStarterTest.java
Fixes #315
Summary:
- the problem is that when reading from a raw Kafka topic the headers are simple byte[], usually the document-to-json agent has always been used inside an in-memory pipeline after the "text-extractor" agent, that produces String headers (String java type)
- the fix is to convert byte[] and to try to keep the original type for other types (Strings, Numbers...)
> Agents: document-to-json: handle copy-properties while reading directly from a topic

- examples/applications/openai-completions/pipeline.yaml
- examples/applications/webcrawler-source/chatbot.yaml
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/ChatCompletionsStep.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/model/config/ChatCompletionsConfig.java
- langstream-core/src/main/java/ai/langstream/impl/agents/ai/GenAIToolKitFunctionAgentProvider.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/ChatCompletionsIT.java
Motivation
Usually when you serve the answer to the end user you want to keep only the answer from the LLM but you still want to log the prompt and the answer in a structure.
Summary:
This patch introduces a new configuration option streaming-response-completion-field, that allows you to modify the contents of the streaming response independently of the main output of the agent.
Usually you are setting "streaming-response-completion-field" to "value", that means that you clear up the whole message and keep only the answer as text.
All the incoming message properties are kept, for instance a session-id or an user-id.
The patch changes the webcrawler and the openai-completions example applications with explanations for this feature
```
topics:
- name: "input-topic"
creation-mode: …
```
> [agents] Chat Completion: allow to override the completion-field for the streaming response (streaming-response-completion-field)

- docker/build.sh
- helm/crds/applications.langstream.ai-v1.yml
- langstream-api/src/main/java/ai/langstream/api/runtime/AgentNode.java
- langstream-api/src/main/java/ai/langstream/api/storage/MetadataOwnerLock.java
- langstream-core/src/main/java/ai/langstream/impl/common/DefaultAgentNode.java
- langstream-k8s-deployer/langstream-k8s-deployer-api/src/main/java/ai/langstream/deployer/k8s/api/crds/apps/ApplicationSpec.java
- langstream-k8s-deployer/langstream-k8s-deployer-api/src/main/java/ai/langstream/deployer/k8s/api/crds/apps/SerializedApplicationInstance.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/agents/AgentResourceUnitConfiguration.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/limits/ApplicationResourceLimitsChecker.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/util/KeyedLockHandler.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/limits/ApplicationResourceLimitsCheckerTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/TenantLimitsChecker.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/BaseController.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/apps/AppController.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/AppControllerIT.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/OperatorExtension.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/KubernetesClusterRuntime.java
- langstream-k8s-storage/src/main/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStore.java
- langstream-runtime/langstream-runtime-impl/src/main/docker/Dockerfile
Implementation of the deployer check of https://github.com/LangStream/langstream/issues/304
* The deployer keeps a local map, counting all the resources used by every application (per tenant)
* The application info are retrieved from the application specs (generated by the execution plan) - this is a new field that will be empty for existing applications
* There's a local lock (per tenant) and only one application can be deployed (meaning both new and updates) at the same time
* When the deployer restarts, once a new application is created/updated/deleted, it recovers the current status by looking at the Application CR. We use the application CR because we want to also count applications that are in error state (before deploying)
* Added new status field in the app custom resource about …
> Deployer: add application resource limits per tenant

- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/util/KubeUtil.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/agents/AgentCustomResourceTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactoryTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/util/KubeUtilTest.java
* Set resource limits with the same value of the requests to ensure the agent code doesn't use more resources than the 
* Ensure in case of OOMKilled the error is reported to the user
Fixes: #313
> Agent pods: set resource limits

- langstream-admin-client/pom.xml
- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/http/ExponentialRetryPolicy.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/http/GenericRetryExecution.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/http/HttpClientProperties.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/http/Retry.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/http/RetryPolicy.java
- langstream-admin-client/src/test/java/ai/langstream/admin/client/http/GenericRetryExecutionTest.java
Fixes: #275
* Added retries logic in the http client. It affects the code download runtime step and all the CLI calls.
* Unfortunately the java11 http client doesn't offer a retry mechanism so I had to implement one from scratch
By default a http call is retried at max 5 times, with a exponential algo (inital 2 seconds, multiplier 1.5)
> Add retries on admin http client

- langstream-api/src/main/java/ai/langstream/api/storage/ApplicationStore.java
- langstream-core/src/main/java/ai/langstream/impl/storage/GlobalMetadataStoreManager.java
- langstream-k8s-common/src/test/java/ai/langstream/impl/k8s/tests/KubeTestServer.java
- langstream-k8s-storage/src/main/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStore.java
- langstream-k8s-storage/src/test/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStoreTest.java
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationService.java
- langstream-webservice/src/main/java/ai/langstream/webservice/common/GlobalMetadataService.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/AppTestHelper.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/ApplicationResourceTest.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/ApplicationServiceResourceLimitTest.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/TenantResourceTest.java
- langstream-webservice/src/test/java/ai/langstream/webservice/security/infrastructure/primary/SecurityConfigurationTest.java
When a tenant is deleted, the namespace is deleted. However the namespace could take time since all the apps have to undeploy successfully.
All the operations on a in-progress tenant should be blocked
Fixes https://github.com/LangStream/langstream/issues/271
> Fix tenants creation while deleting is in progress

- langstream-api-gateway/pom.xml
- langstream-api-gateway/src/main/resources/application.properties
- langstream-k8s-common/pom.xml
- langstream-k8s-deployer/langstream-k8s-deployer-operator/pom.xml
- langstream-webservice/pom.xml
- langstream-webservice/src/main/resources/application.properties
Added micrometer prometheus registry in all the services. By default they are configured in the main port of the service. 
Control plane: /management/prometheus
Api Gateway: /management/prometheus
Deployer: /q/metrics
All the endpoints are in prometheus format. 
For now the services only expose jvm metrics.
> Expose metrics endpoint for all the services

- langstream-api/src/main/java/ai/langstream/api/model/Module.java
- langstream-api/src/main/java/ai/langstream/api/model/TopicDefinition.java
- langstream-core/src/main/java/ai/langstream/impl/common/ApplicationPlaceholderResolver.java
- langstream-core/src/test/java/ai/langstream/impl/common/ApplicationPlaceholderResolverTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/ChatCompletionsIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/PlaceholderEndToEndTest.java
Summary:
- allow to use {{{globals.topicname}} in topic definitions
- this works as expected while declaring topics, using topic references in "input" and "output" and in the configuration of the agents (for instance stream-to-topic in the ai-chat-completions agent)
> [configuration] Allow to use global variables for topic names

- langstream-cli/pom.xml
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootAppCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootGatewayCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootTenantCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/VersionProvider.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/DeleteApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/DownloadApplicationCodeCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/GetApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/GetApplicationLogsCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/ListApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/configure/ConfigureCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/ChatGatewayCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/ConsumeGatewayCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/ProduceGatewayCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/tenants/CreateTenantCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/tenants/DeleteTenantCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/tenants/GetTenantCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/tenants/ListTenantCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/tenants/PutTenantCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/tenants/UpdateTenantCmd.java
- pom.xml
Fixes #325
* The CLI -V command now reads the jar manifest and get the version (maven version) + git revision
Result is
```
$ langstream -V        
LangStream CLI 0.0.11-SNAPSHOT (f89913a6)
```
* Fixed usage of header instead of description for every command
> Add CLI version (langstream -V)

- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/agents/AgentResourceUnitConfiguration.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactoryTest.java
The default memory limit for 1 unit is 256M. This value is too low for some builtin agents and they get killed by k8s.
> Set default unit memory to 512M

- examples/secrets/secrets.yaml
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/AppsCmdTest.java
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
- langstream-core/src/test/java/ai/langstream/impl/parser/ModelBuilderTest.java
Summary:
- in secrets.yaml and instance.yaml you can now refer to local files using the <file:xxx> syntax
- the file is automatically read from the local file system and copied into the YAML file
- text files are kept as they are
- binary files (for instance secure bundle zip files) are base64 encoded and prepended with the "base64:" prefix
Sample usage:
```
secrets:
- name: vertex-ai
id: vertex-ai
data:
url: https://us-central1-aiplatform.googleapis.com
token: xxx
serviceAccountJson: "<file:service-account.json>"
region: us-central1
project: myproject
- name: astra
id: astra
data:
username: xxx
password: xxx
secureBundle: "<file:secure-connect-bundle.zip>"
```
Please note that this is a CLI only feature, we will have to implement support for this syntax in the VS Code extension …
> [cli] Allow to refer to local files in secrets.yaml and in instance.yaml using <file:xxx> syntax

- examples/applications/kafka-connect/pipeline.yaml
- examples/applications/text-processing/write-to-astra.yaml
- examples/applications/webcrawler-source/write-to-astra.yaml
- langstream-e2e-tests/src/test/resources/apps/cassandra-sink/pipeline.yaml
Summary:
- now that we enforce the resource limits on K8S the Kafka Connect Sink for Cassandra started to go OOM
- this patch changes the resource requirements to 2 units on every CassandraSinkConnector in the examples and in the e2e tests
> Cassandra Sink: set 2 resource units in all the examples

- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/kafka_connection.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/tests/test_kafka_connection.py
* Fix committed offset must be last message offset + 1
* Add on_assign/on_revoke
* Add tests
> Fix Python Kafka offsets and add tests

- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/WebCrawlerSource.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/GenAIToolKitAgent.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/VectorDBSinkAgent.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/cassandra/CassandraWriter.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/pinecone/PineconeWriter.java
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/CassandraWriterTest.java
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/PineconeWriterTest.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ProduceHandler.java
- langstream-api/src/main/java/ai/langstream/api/database/VectorDatabaseWriter.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentCodeAndLoader.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentSink.java
- langstream-api/src/main/java/ai/langstream/api/runner/topics/TopicProducer.java
- langstream-kafka-connect/src/main/java/ai/langstream/kafkaconnect/KafkaConnectSinkAgent.java
- langstream-kafka/src/main/java/ai/langstream/kafka/runner/KafkaConsumerWrapper.java
- langstream-kafka/src/main/java/ai/langstream/kafka/runner/KafkaProducerWrapper.java
- langstream-kafka/src/main/java/ai/langstream/kafka/runner/KafkaReaderWrapper.java
- langstream-kafka/src/test/java/ai/langstream/kafka/KafkaConsumerTest.java
- langstream-pulsar/src/main/java/ai/langstream/pulsar/runner/PulsarTopicConnectionsRuntimeProvider.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunnerStarter.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/SourceRecordTracker.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/TopicConsumerSource.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/TopicProducerSink.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/mockagents/MockProcessorAgentsCodeProvider.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/pulsar/PulsarRunnerDockerTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/agent/AgentRunnerStarterTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/agent/AgentRunnerTest.java
Summary:
- rework the internal Sink API to be fully async
- Kafka Topic Sink
- Kafka Connect Sinks
- Cassandra Sink
- Pinecone Sink (not really async)
- now that everything is async we have to wait for all the messages produced by the Source to be processed before shutting down the process (or the test)
> Implement fully asynchronous Sinks and graceful pod shutdown (Java runtime)

- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/__main__.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/kafka_connection.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/runtime.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/tests/test_runtime.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/topic_connector.py
> Add Python logging with same format as Java

- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-api/src/main/java/ai/langstream/api/model/AssetDefinition.java
- langstream-api/src/main/java/ai/langstream/api/model/Module.java
- langstream-api/src/main/java/ai/langstream/api/runner/assets/AssetManager.java
- langstream-api/src/main/java/ai/langstream/api/runner/assets/AssetManagerAndLoader.java
- langstream-api/src/main/java/ai/langstream/api/runner/assets/AssetManagerProvider.java
- langstream-api/src/main/java/ai/langstream/api/runner/assets/AssetManagerRegistry.java
- langstream-api/src/main/java/ai/langstream/api/runtime/DeployContext.java
- langstream-api/src/main/java/ai/langstream/api/runtime/ExecutionPlan.java
- langstream-core/src/main/java/ai/langstream/impl/common/ApplicationPlaceholderResolver.java
- langstream-core/src/main/java/ai/langstream/impl/common/BasicClusterRuntime.java
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
- langstream-core/src/test/java/ai/langstream/model/parser/AssetsTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/AgentControllerIT.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/KubernetesClusterRuntime.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/KubernetesClusterRuntimeDockerTest.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/KubernetesClusterRuntimeTest.java
- langstream-k8s-storage/src/test/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStoreLogsTest.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/nar/NarFileHandler.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/deployer/RuntimeDeployer.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/assets/DeployAssetsTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/mockagents/MockAssetManagerCodeProvider.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/LoadAgentCodeTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/LoadAssertManagerCodeTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/agent/AgentRunnerStarterTest.java
- langstream-runtime/langstream-runtime-impl/src/test/resources/META-INF/services/ai.langstream.api.runner.assets.AssetManagerProvider
Fixes #353 
Summary:
- Add the new concept of "asset"
- An Asset is an external resource that is handled by the LangStream application
- At deploy time and undeploy time the "init job" and the "clean up job" can execute some code, dependent on the type of the asset
The main use case here is to create tables of vector databases in order to fully set up the application when you deploy it 
This is a preliminary PR that builds all the infrastructure to make Assets work.
The next step is to implement the "cassandra-table" AssetManager (and maybe validation at the planner side of the available  asset types)
> [new feature] Implement Assets - part 1

- conf/cli.yaml
- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-cli/src/main/java/ai/langstream/cli/NamedProfile.java
- langstream-cli/src/main/java/ai/langstream/cli/Profile.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/BaseCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/DownloadApplicationCodeCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/configure/ConfigureCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/BaseGatewayCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/BaseProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/CreateUpdateProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/DeleteProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/GetCurrentProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/GetProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/ImportProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/ListProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/SetCurrentProfileCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/AppsCmdTest.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/CommandTestBase.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/ProfilesCmdTest.java
Profiles are stored in the cli configuration yaml file.
There's a default profile which is "virtual" and uses the current cli.yaml configuration top-level entries
*Create a profile with inline values*
```
langstream profiles create my-prof --web-service-url xx --tenant xx --token xx  --api-gateway-url xx
```
*Create a profile with inline values and set it as current*
```
langstream profiles create my-prof --web-service-url xx --tenant xx --token xx  --api-gateway-url xx --set-current
```
*Update a profile with inline values*
```
langstream profiles update my-prof --web-service-url xx --tenant xx --token xx  --api-gateway-url xx
```
*Create a profile from json file*
```
langstream profiles import my-prof -f <file.json>
```
*Create a profile from inline json*
```
langstream profiles import …
```
> Cli: add profiles

- bin/langstream
- langstream-cli/pom.xml
- langstream-cli/src/main/docker/Dockerfile
- langstream-cli/src/main/java/ai/langstream/cli/commands/BaseCmd.java
* By default, it uses the config file at `$HOME/.langstream/config`. If it doesn't exist, it gets created.
* User can still pass `--conf` to use a different config file
* conf/cli.yaml is anymore included in the zip/docker since it's not necessary
* default values are now set by the cli directly instead of being retrieved by the file 
This is breaking change since the current config file will be ignored and new one will be used. 
Note that the command ´bin/langstream´ is a bit different from the one that you install. The former injects the --conf parameter by using the env LANGSTREAM_CLI_CONF. Now it defaults to the global one as well.
Since that command is likely to be used during development, I added a info at the cli startup
```
Using global CLI config file. To use the dev config file, …
```
> Cli: use global config file by default

- examples/applications/astradb-sink/README.md
- examples/applications/astradb-sink/configuration.yaml
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/datasource/CassandraDataSource.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/cassandra/CassandraWriter.java
- langstream-core/src/main/java/ai/langstream/impl/assets/CassandraAssetsProvider.java
- langstream-core/src/main/java/ai/langstream/impl/common/AbstractAssetProvider.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/AstraDBAssetQueryWriteIT.java
Summary:
- now that we can use the Astra DevOps API it is easy to download the Secure bundle automatically
- the user must provide the "token" and the "database" in the DataSource configuration
- this works for the query-vector-db, vector-db-sink and the astra-keyspace and cassandra-table assets
configuration.yaml
```
configuration:
resources:
- type: "vector-database"
name: "AstraDatasource"
configuration:
service: "astra"
clientId: "{{{ secrets.astra.clientId }}}"
secret: "{{{ secrets.astra.secret }}}"
token: "{{{ secrets.astra.token }}}"
database: "{{{ secrets.astra.database }}}"
environment: "{{{ secrets.astra.environment }}}"
```
"environment" is by default PROD and it can be PROD, STAGING, DEV, this is a Datastax only thing, because we use the DEV databases.
I would keep it because …
> Vector DB Support: download automatically the AstraDB secure bundle

- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClientLogger.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/HttpRequestFailedException.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/http/HttpClientFacade.java
- langstream-cli/src/main/java/ai/langstream/cli/LangStreamCLI.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/BaseCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmdTest.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentCodeDownloader.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/deployer/RuntimeDeployer.java
- Each value (-app, -i, -s) if it starts with https:// will be downloaded and included in the zip. If the request fails the command fails as well
- plain HTTP is not supported
> Cli: allow to pass remote file - HTTPS

- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/http/HttpClientFacade.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/util/Slf4jLAdminClientLogger.java
- langstream-cli/pom.xml
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/GithubRepositoryDownloader.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/GithubRepositoryDownloaderTest.java
* Accepts Github UI links to directory or files. The expected flow is that the user copy the url from the github UI and put it in the input
*Get example application from this repo*
```
langstream apps deploy test -app https://github.com/LangStream/langstream/tree/main/examples/applications/astradb-sink
```
*Get example application from this repo of a specific tag*
```
langstream apps deploy test -app https://github.com/LangStream/langstream/tree/v0.0.13/examples/applications/astradb-sink
```
> Cli: allow to pass remote file - Github

- langstream-api/src/main/java/ai/langstream/api/model/Application.java
- langstream-api/src/main/java/ai/langstream/api/runtime/ComputeClusterRuntime.java
- langstream-api/src/main/java/ai/langstream/api/runtime/PluginsRegistry.java
- langstream-api/src/main/java/ai/langstream/api/runtime/ResourceNodeProvider.java
- langstream-core/src/main/java/ai/langstream/impl/agents/ai/GenAIToolKitFunctionAgentProvider.java
- langstream-core/src/main/java/ai/langstream/impl/common/AbstractAgentProvider.java
- langstream-core/src/main/java/ai/langstream/impl/common/AbstractAssetProvider.java
- langstream-core/src/main/java/ai/langstream/impl/common/BasicClusterRuntime.java
- langstream-core/src/main/java/ai/langstream/impl/resources/AIProvidersResourceProvider.java
- langstream-core/src/main/java/ai/langstream/impl/resources/DataSourceResourceProvider.java
- langstream-core/src/main/java/ai/langstream/impl/resources/VectorDatabaseResourceProvider.java
- langstream-core/src/main/resources/META-INF/services/ai.langstream.api.runtime.ResourceNodeProvider
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/QueryVectorDBAgentProvider.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/testagents/TestGenericAgentProvider.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/testagents/TestGenericSinkAgentProvider.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/testagents/TestGenericSourceAgentProvider.java
Summary:
This patch introduces a mechanism to implement validation of "resource", in order to make it happen on the planner side, as soon as possible, and provide feedback on wrong configuration as soon as possible.
With the basic validation introduced in this PR we validate that:
- the "type" is a well-known type
- for "datasource" and "vector-database" resources you configure a "service" property
Follow up patches will add specific validations for all the known types of resources
> [resources] Introduce planner side validation of resources

- langstream-api/src/main/java/ai/langstream/api/util/ConfigurationUtils.java
- langstream-core/src/main/java/ai/langstream/impl/assets/CassandraAssetsProvider.java
- langstream-core/src/main/java/ai/langstream/impl/common/AbstractAssetProvider.java
- langstream-core/src/main/java/ai/langstream/impl/resources/AIProvidersResourceProvider.java
- langstream-core/src/main/java/ai/langstream/impl/resources/DataSourceResourceProvider.java
- langstream-core/src/main/java/ai/langstream/impl/resources/VectorDatabaseResourceProvider.java
- langstream-core/src/test/java/ai/langstream/impl/resources/ResourceNodeProviderTest.java
Summary:
- validate as much as possible all the known resource types: datasource (astra, cassandra, pinecone, generic JDBC), vector-database (astra, pinecone, cassandra), openai-configuration, vertex-configuration, hugging-face-configuration
- the intent is to fail invalid configurations at deploy time
Notes:
- we are validating resources that are actually used by agents, this allows to have some demo configuration files with empty values: they won't fail the deploy as long as they are not used
- we cannot connect to the services at deploy time, this is because the actual connection can be performed ONLY from the agent pods, and not from the Control Plane, due to security reasons (agent runners run in special security contexts) and also because the .nar files with the drivers are only …
> Resource: add static validation for all the known resource types

- docker/build.sh
- examples/instances/astra.yaml
- examples/instances/kafka-docker.yaml
- examples/secrets/secrets.yaml
- langstream-cli/src/main/java/ai/langstream/cli/commands/BaseCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootAppCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootDockerCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/BaseDockerCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-runtime/langstream-runtime-tester/pom.xml
- langstream-runtime/langstream-runtime-tester/src/main/assemble/entrypoint.sh
- langstream-runtime/langstream-runtime-tester/src/main/assemble/langstream-runtime-tester.xml
- langstream-runtime/langstream-runtime-tester/src/main/docker/Dockerfile
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/KubeTestServer.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/LocalApplicationRunner.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/Main.java
- langstream-runtime/pom.xml
Goals:
allow users to quickly iterate over the configurations without needing to deploy the application to a kubernetes cluster
Summary:
- new docker image langstream-runtime-tester that allows you to run a single LangStream application on the local enviroment, on a single docker container
How to run the tool:
`bin/langstream docker run -app /path/to/app -i /path/to/instance -s /path/to-secrets --start-broker=true|false --start-s3=true|false`
it is the same command as "apps deploy" but you use "local-run" instead of "deploy".
As the environment is ephemeral you must always pass the instance.yaml and the secrets.yaml files
By default we also start Kafka and Minio, you can control them by using --start-broker and --start-s3
Limitations of the "local mode":
- this is not for production, only …
> [cli] Add a tool to run locally an application on docker

- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/AuthenticationInterceptor.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/AbstractHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ConsumeHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ProduceHandler.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/websocket/handlers/ProduceConsumeHandlerTest.java
- langstream-api/src/main/java/ai/langstream/api/model/Gateway.java
- langstream-core/src/main/java/ai/langstream/impl/common/ApplicationPlaceholderResolver.java
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
- langstream-core/src/test/java/ai/langstream/impl/common/ApplicationPlaceholderResolverTest.java
- langstream-core/src/test/java/ai/langstream/impl/parser/ModelBuilderTest.java
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationService.java
Moved Gateway class from record to class in order to easily handle new properties. 
Also moved tests to use builder instead of constructor
> Internal refactor for Gateway

- examples/secrets/secrets.yaml
The default provider should be OpenAI, not Azure. The average user is more likely to have an OpenAI key, which is quite easy to get, than an Azure key. By defaulting to `openai` there is one less env var to set for in the quick start path.
> Change the default provider to OpenAI

- .github/workflows/ci.yml
- .github/workflows/release.yml
- docker/build.sh
- examples/applications/webcrawler-source/crawler.yaml
- langstream-runtime/langstream-runtime-base-docker-image/pom.xml
- langstream-runtime/langstream-runtime-base-docker-image/src/main/docker/Dockerfile
- langstream-runtime/langstream-runtime-impl/pom.xml
- langstream-runtime/langstream-runtime-impl/src/main/docker/Dockerfile
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/nar/NarFileHandler.java
- langstream-runtime/pom.xml
Summary:
Changes to the docker images:
- split the build of the langstream-runtime image into two steps (langstream-runtime-base and langstream-runtime)
- langstream-runtime-base  contains only the OS, the JDK, Python and some system tools
- with this split rebuilding the images locally and uploading them to minikube is faster as you have to not rebuild 1GB of docker image every time
Changes to logging:
- remove all the logging due to classloading
- add logging every 5 seconds about the number of records in the pipeline and the amount of memory used
> [agentrunner] Split the docker image and clean up the logs

- helm/crds/agents.langstream.ai-v1.yml
- langstream-k8s-deployer/langstream-k8s-deployer-api/src/main/java/ai/langstream/deployer/k8s/api/crds/agents/AgentStatus.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/ResolvedDeployerConfiguration.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/BaseController.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/agents/AgentController.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/apps/AppController.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/AgentControllerIT.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/OperatorExtension.java
- langstream-runtime/langstream-runtime-impl/pom.xml
Currently if the deployer gets upgraded/restarted, the new config is applied to ALL the agents/statefulsets. 
That also means that every time the runtime version gets upgraded in the deployer, all the executors restart with the new runtime version.
There are problems with this policy:
1. All the executors get restarted when a system upgrade is performed. This is very bad for the user experience/performance/stability.
2. The executor should continue running that particular version of that the runtime. An agent change could break existing applications. 
For the point 2, in the future it could implemented a flag "auto-update" to get the new runtime image whenever the *application* is upgraded - not the deployer.
Changes:
* Save current configuration (only the relevant and public part) in the …
> Ensure existing agents are not affected by deployer config changes

- .github/workflows/needs-doc.yml
This [workflow](https://github.com/actions/add-to-project) adds pull requests with the `needs-doc` label to the documentation backlog project.
The ADD_TO_PROJECT_PAT is used for the action.
It should keep the docs backlog updated with less noise for all.
> Add workflow for needs-doc label

- examples/applications/gateway-authentication/gateways.yaml
- examples/instances/kafka-docker.yaml
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/WebSocketConfig.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/AbstractHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ChatHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ProduceHandler.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/websocket/handlers/ProduceConsumeHandlerTest.java
- langstream-api/src/main/java/ai/langstream/api/model/Gateway.java
- langstream-cli/src/main/java/ai/langstream/cli/api/model/Gateways.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/BaseGatewayCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/ChatGatewayCmd.java
- langstream-core/src/main/java/ai/langstream/impl/common/ApplicationPlaceholderResolver.java
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
In many cases, the application declares two gateways for both producing and consuming messages at the end and beginning of the pipeline. This results in two connection opened to the gateway and hard configuration in the CLI. 
It would be useful to have a simpler gateway that does both in only one connection and optimized for the chat-like communication.
Changes: 
* Added a new type 'chat' to the gateway types
```
- id: chat
type: chat
authentication:
provider: google
configuration:
clientId: "{{ secrets.google.client-id }}"
chat-options:
headers:
- value-from-parameters: session-id
- value-from-authentication: user-id
answers-topic: output-topic
user-parameter: subject
```
*questions-topic*: (required). Topic for producing messages. Typically the input topic of the pipeline …
> Introduce new gateway type: 'chat'

- langstream-api-gateway/pom.xml
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/ApplicationStartupTraces.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/LangStreamApiGateway.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/BaseDockerCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-tester/pom.xml
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/InMemoryApplicationStore.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/KubeTestServer.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/LocalApplicationRunner.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/Main.java
- langstream-runtime/langstream-runtime-tester/src/main/resources/META-INF/services/ai.langstream.api.storage.ApplicationStore
- langstream-runtime/langstream-runtime-tester/src/main/resources/gateway.application.properties
- langstream-runtime/langstream-runtime-tester/src/main/resources/webservice.application.properties
- langstream-webservice/pom.xml
- langstream-webservice/src/main/java/ai/langstream/webservice/LangStreamControlPlaneWebApplication.java
- pom.xml
Summary:
- Now with the "langstream run docker" command the container runs also the Gateway API service and the Control Plane service
- This way when you run the application locally you can have almost the same user experience as while running on K8S or on a cloud provider
- Now you can also customise the "docker run" command by setting the name of the "docker" CLI command (--docker-command), resource requests (--memory, --cpus) and also you can pass additional arguments (--docker-additional-args)
- You can also now filter your application and run only one "agent" (actually and "executor") with the "--only-agent" option
Changes:
- build the jar artifact for the gateway and the webservice project
- implement the things above
- reduce some logging (we are printing too much on the logs, …
> [cli] "langstream run docker" command: start the webservices and other improvements

- .github/workflows/release.yml
- examples/instances/kafka-docker.yaml
- langstream-cli/src/main/java/ai/langstream/cli/commands/VersionProvider.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/ChatGatewayCmd.java
Summary:
- allow to choose the docker image to use when running the "docker run" command
- fix a regression in the examples/instances/kafka-docker.yaml file
- fix a regression in the "gateway chat" command
> [docker run] Make the version configurable

- langstream-kafka-runtime/src/main/java/ai/langstream/kafka/runner/KafkaProducerWrapper.java
- langstream-kafka-runtime/src/test/java/ai/langstream/kafka/KafkaConsumerTest.java
Summary:
Use a smarter algorithm to cache the Serialiser while producing to a Kafka topic
> [kafka] Support writing messages with different schemas

- .github/workflows/ci.yml
- dev/prepare-minikube-for-e2e-tests.sh
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/cassandra/CassandraAssetsManagerProvider.java
- langstream-api/src/main/java/ai/langstream/api/model/TopicDefinition.java
- langstream-api/src/main/java/ai/langstream/api/runner/assets/AssetManager.java
- langstream-api/src/main/java/ai/langstream/api/runner/assets/AssetManagerAndLoader.java
- langstream-core/src/main/java/ai/langstream/impl/common/BasicClusterRuntime.java
- langstream-core/src/main/java/ai/langstream/impl/deploy/ApplicationDeployer.java
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/BaseEndToEndTest.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/PythonFunctionIT.java
- langstream-e2e-tests/src/test/resources/apps/python-processor/pipeline.yaml
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/apps/AppResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/apps/AppResourcesFactoryTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/apps/AppController.java
- langstream-kafka-runtime/src/main/java/ai/langstream/kafka/runner/KafkaTopicConnectionsRuntime.java
- langstream-kafka-runtime/src/test/java/ai/langstream/kafka/KafkaClusterRuntimeDockerTest.java
- langstream-kafka-runtime/src/test/java/ai/langstream/kafka/KafkaConsumerTest.java
- langstream-kafka/src/main/java/ai/langstream/kafka/runtime/KafkaStreamingClusterRuntime.java
- langstream-kafka/src/main/java/ai/langstream/kafka/runtime/KafkaTopic.java
- langstream-pulsar-runtime/src/main/java/ai/langstream/pulsar/runner/PulsarTopicConnectionsRuntimeProvider.java
- langstream-pulsar/src/main/java/ai/langstream/pulsar/PulsarStreamingClusterRuntime.java
- langstream-pulsar/src/main/java/ai/langstream/pulsar/PulsarTopic.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/application/ApplicationSetupRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/application/ApplicationSetupRunnerStarter.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/mockagents/MockAssetManagerCodeProvider.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/ApplicationServiceValidateUpdateTest.java
Changes:
* New option in the topic section `deletion-mode`
Possible values are `none`, `delete`
`none` is the default value.
`none` means to keep the topic when the app is deleted
`delete` means to delete the topic when the app is deleted
Note that `delete` works only if the `creation-mode` is `create-if-not-exists`. This is because in that case we know that we can actually manage that topic inside the langstream app.
Example:
```
topics:
- name: input-topic
- name: output-topic
deletion-mode: delete
```
* Added a new setup-cleanup job right after the runtime deployer cleanup. The latter only deletes the agents. The new job is responsible to delete the topics (and the assets very soon)
* Added the app deletion in the …
> Introduce deletion-mode for topics

- dev/stop-port-forward.sh
- langstream-agents/langstream-ai-agents/pom.xml
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/services/impl/OpenAICompletionService.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/util/TransformFunctionUtil.java
- langstream-agents/langstream-ai-agents/src/test/java/ai/langstream/ai/agents/services/impl/OpenAIProviderTest.java
- langstream-agents/langstream-ai-agents/src/test/java/com/datastax/oss/pulsar/functions/transforms/GenAITest.java
- langstream-core/src/main/java/ai/langstream/impl/deploy/ApplicationDeployer.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/ChatCompletionsIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/ComputeEmbeddingsIT.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/LocalApplicationRunner.java
- langstream-runtime/langstream-runtime-tester/src/main/resources/gateway.application.properties
- pom.xml
Summary:
- update the OpenAI client
- update the Azure SDK
> Upgrade OpenAI client

- langstream-core/src/main/java/ai/langstream/impl/common/AbstractAssetProvider.java
Based on this error message:
"detail" : "Missing required field 'token' in  assert definition, type=astra-keyspace, name=keyspace, id=keyspace",
Fixing extra space and spelling.
> Fix typo in error message

- langstream-agents/langstream-agent-grpc/pom.xml
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/GrpcAgentProcessor.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/GrpcAgentsCodeProvider.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/PythonGrpcAgentProcessor.java
- langstream-agents/langstream-agent-grpc/src/main/proto/processor.proto
- langstream-agents/langstream-agent-grpc/src/main/resources/META-INF/ai.langstream.agents.index
- langstream-agents/langstream-agent-grpc/src/main/resources/META-INF/services/ai.langstream.api.runner.code.AgentCodeProvider
- langstream-agents/langstream-agent-grpc/src/test/java/ai/langstream/agents/grpc/GrpcAgentProcessorTest.java
- langstream-agents/pom.xml
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentContext.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/GrpcAgentsProvider.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/resources/META-INF/services/ai.langstream.api.runtime.AgentNodeProvider
- langstream-runtime/langstream-runtime-impl/pom.xml
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- pom.xml
For preliminary review.
Still need to:
* Put the agent in its own artifact
* Build a NAR
* Resolve TODOs
> Add gRPC processor agent

- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/cassandra/CassandraAssetsManagerProvider.java
- langstream-api/src/main/java/ai/langstream/api/model/AssetDefinition.java
- langstream-api/src/main/java/ai/langstream/api/runner/assets/AssetManager.java
- langstream-api/src/main/java/ai/langstream/api/runner/assets/AssetManagerAndLoader.java
- langstream-core/src/main/java/ai/langstream/impl/assets/CassandraAssetsProvider.java
- langstream-core/src/main/java/ai/langstream/impl/common/AbstractAssetProvider.java
- langstream-core/src/main/java/ai/langstream/impl/common/BasicClusterRuntime.java
- langstream-core/src/main/java/ai/langstream/impl/deploy/ApplicationDeployer.java
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/CassandraSinkIT.java
- langstream-e2e-tests/src/test/resources/apps/cassandra-sink/configuration.yaml
- langstream-e2e-tests/src/test/resources/apps/cassandra-sink/pipeline.yaml
- langstream-e2e-tests/src/test/resources/secrets/secret1.yaml
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/assets/DeployAssetsTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/AstraDBAssetQueryWriteIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/CassandraAssetQueryWriteIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/mockagents/MockAssetManagerCodeProvider.java
Same of https://github.com/LangStream/langstream/pull/418 but for assets.
new field `deletion-mode: none|delete`. Default is none
```
assets:
- name: "vsearch-keyspace"
asset-type: "cassandra-keyspace"
deletion-mode: delete
config:
keyspace: "vsearch"
datasource: "CassandraDatasource"
create-statements:
- "CREATE KEYSPACE vsearch WITH REPLICATION = {'class' : 'SimpleStrategy','replication_factor' : 1};"
```
> Introduce deletion-mode for assets

- langstream-api/src/main/java/ai/langstream/api/runner/topics/TopicConnectionsRuntimeAndLoader.java
- langstream-core/src/main/java/ai/langstream/impl/nar/NarFileHandler.java
- langstream-kafka-runtime/src/main/java/ai/langstream/kafka/runner/KafkaConsumerWrapper.java
- langstream-kafka-runtime/src/main/java/ai/langstream/kafka/runner/KafkaProducerWrapper.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
Fixes this error 
```
20:09:54.047 [main] INFO  a.l.runtime.agent.AgentRunnerStarter -- Error, NOW SLEEPING                                                  │
│ runtime org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient                                                          │
│ runtime     at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:551)                                       │
│ runtime     at org.apache.kafka.clients.admin.Admin.create(Admin.java:144)                                                                     │
│ runtime     at org.apache.kafka.connect.util.TopicAdmin.<init>(TopicAdmin.java:282)                                                            │
│ runtime     at …
```
> Fix topics runtime classloader

- examples/applications/openai-completions/gateways.yaml
- examples/applications/openai-completions/pipeline.yaml
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/ChatGatewayCmd.java
With this update, dots are not printed in the streaming output if there is a pause in the generation of new tokens. Also some tweaks to the openai-completions example to make for a slicker demo.
> Improved streaming chat output

- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/services/impl/OpenAICompletionService.java
- langstream-runtime/langstream-runtime-tester/pom.xml
Fixes #439 
Summary:
- remove the Azure Blob dependency from the docker-runtime-tester, as it bring the Azure SDK that generate conflicts with the OpenAI Async client
> [docker run] Fix loading of OpenAI Async client - use the Netty provider instead of okhttp

- langstream-e2e-tests/src/test/java/ai/langstream/tests/BaseEndToEndTest.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/WebCrawlerToVectorIT.java
- langstream-e2e-tests/src/test/resources/apps/webcrawler-to-vector/chatbot.yaml
- langstream-e2e-tests/src/test/resources/apps/webcrawler-to-vector/configuration.yaml
- langstream-e2e-tests/src/test/resources/apps/webcrawler-to-vector/crawler.yaml
- langstream-e2e-tests/src/test/resources/apps/webcrawler-to-vector/gateways.yaml
- langstream-e2e-tests/src/test/resources/apps/webcrawler-to-vector/write-to-vector.yaml
- langstream-e2e-tests/src/test/resources/secrets/secret1.yaml
It uses a bunch of agents:
* webcrawler source (uses minio for status)
* text-extractor
* language-detector
* text-splitter
* document-to-json
* compute
* compute-ai-embeddings
* query (astra + vector)
* ai-chat-completions
* vector-db-sink (astra)
It's disabled on CI, to run it you have to export all of these
```
export OPEN_AI_ACCESS_KEY=
export OPEN_AI_URL=
export OPEN_AI_EMBEDDINGS_MODEL=
export OPEN_AI_CHAT_COMPLETIONS_MODEL=
export OPEN_AI_PROVIDER=
export ASTRA_TOKEN=
export ASTRA_CLIENT_ID=
export ASTRA_SECRET=
export ASTRA_SECURE_BUNDLE=
export ASTRA_ENVIRONMENT=
export ASTRA_DATABASE=
```
> Add e2e test with WebCrawler + embeddings + vector sink + completions

- langstream-cli/src/main/java/ai/langstream/cli/LangStreamCLIConfig.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/BaseProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/CreateUpdateProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/DeleteProfileCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/profiles/ImportProfileCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/ProfilesCmdTest.java
Currently it's not possible to update the default profile. This is not very handy. There's no strong reason to block the update
Changes:
* Now the default profile can be modified with `update` and `import`. It still cannot be deleted
> CLI: Allow updates to the default profile

- langstream-core/src/test/resources/application1/pipeline1.yaml
- langstream-kafka-runtime/src/main/java/ai/langstream/kafka/runner/KafkaTopicConnectionsRuntime.java
Summary:
- fix passing the replication-factor option to the creation of Kafka topics
- enhance some examples about AVRO schemas
> [kafka] Fix passing the replication-factor to create topics

- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/ComputeAIEmbeddingsStep.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/embeddings/OpenAIEmbeddingsService.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/model/config/ComputeAIEmbeddingsConfig.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/util/TransformFunctionUtil.java
- langstream-agents/langstream-ai-agents/src/test/java/com/datastax/oss/streaming/ai/ComputeAIEmbeddingsTest.java
- langstream-api/src/main/java/ai/langstream/api/util/BatchExecutor.java
- langstream-api/src/main/java/ai/langstream/api/util/OrderedAsyncBatchExecutor.java
- langstream-api/src/test/java/ai/langstream/api/BatchExecutorTest.java
- langstream-api/src/test/java/ai/langstream/api/OrderedAsyncBatchExecutorTest.java
- langstream-core/src/main/java/ai/langstream/impl/agents/ai/GenAIToolKitFunctionAgentProvider.java
- langstream-runtime/langstream-runtime-impl/pom.xml
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/ComputeEmbeddingsIT.java
Summary:
This patch comes with two contributions:
- OrderedAsyncBatchExecutor
- Using OrderedAsyncBatchExecutor in the Compute Embeddings Agent
## OrderedAsyncBatchExecutor
This  patch introduces an utility to implement batch computations, OrderedAsyncBatchExecutor, but with asynchronous completion and strict ordering guarantees.
This utility will be used by all the async agents, especially the ComputeEmbedding agent, the AI Chat completions, the Query  agents and the Vector DB Sink agents.
The idea is that for each record we compute an hash function that maps the record to a bucket. 
Each bucket processes the record in order by passing them in batches to an external processor.
The processor is supposed to be asynchronous and it must acknowledge the completion of the execution for the …
> [compute-ai-embeddings] Compute Embeddings Agent: execute calls asynchronously and in batches while preserving per-key ordering 

- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/WebCrawlerSource.java
- langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/WebCrawlerSourceTest.java
Summary:
- we recently changed the format of the JSON file with the status of the Web Crawler, this broke compatibility and you cannot easily upgrade the application to the newer version
- with this change in case of a broken JSON file (or with an incompatible format) we ignore the file and start from scratch
For docs:
- change the default of max-depth to 50
> [webcrawler] Do not fail in case of unknown properties in the JSON file (handle backward compatibility)

- langstream-api-gateway/pom.xml
```
Warning:  Some problems were encountered while building the effective model for ai.langstream:langstream-api-gateway:jar:0.0.22-SNAPSHOT
Warning:  The expression $***pom.build.directory*** is deprecated. Please use $***project.build.directory*** instead.
```
> Fix compile warning

- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/agents/AgentResourceUnitConfiguration.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactoryTest.java
Currently the executor doesn't have any readiness/liveness probe. 
The main problem is that the application status relies on the statefulset ready status. Therefore an app goes into DEPLOYED even if the executor has not started to consume messages yet.
This problem is more evident with the latest improvements on the classpath. The extraction of NAR agents/streaming runtime can take time in low-resource environments.
As user I'd expect that if an app is DEPLOYED, then I can use gateways and get answers in relevant time. 
Changes:
* This solution introduces readiness/liveness probes that check the metrics endpoint. The http server is setup only after all the executor unpackaging has been done and right before creating the streaming consumer.
* The values are configurable in the deployer …
> Executor pod: set liveness and readiness probe

- examples/applications/query-milvus/configuration.yaml
- examples/secrets/secrets.yaml
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/milvus/MilvusAssetsManagerProvider.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/milvus/MilvusDataSource.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/milvus/MilvusWriter.java
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/MilvusDataSourceTest.java
Summary:
- add support for Milvus Cloud
- allow to configure url and token (instead of username/password/host/port)
- allow to configure write-mode: upsert|delete-insert because the service still doesn't support Upserts
> Add support for Milvus Cloud - Zillis

- examples/applications/vertexai-text-completions/README.md
- examples/applications/vertexai-text-completions/configuration.yaml
- examples/applications/vertexai-text-completions/gateways.yaml
- examples/applications/vertexai-text-completions/pipeline.yaml
- examples/secrets/secrets.yaml
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/services/impl/HuggingFaceProvider.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/services/impl/VertexAIProvider.java
- langstream-agents/langstream-ai-agents/src/test/java/ai/langstream/ai/agents/services/impl/VertexAIProviderTest.java
* Implemented `ai-text-completions` agent for vertexAI. Only one prompt must be specified. The API is the same and Vertex inference the response depending on the model. Using a text model in the chat agent will cause runtime errors. Using a chat model in the text agent will cause runtime errors.
* Implemented `ai-text-completions` agent for Hugging face. The API is the same as the chat-completions but in this way we support switching between providers while doing tests
> Implement ai-text-completions for VertexAI and HuggingFace inf

- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/datasource/impl/JdbcDataSourceProvider.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/datasource/QueryStepDataSource.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/util/TransformFunctionUtil.java
- langstream-agents/langstream-ai-agents/src/test/java/ai/langstream/ai/agents/datasource/JdbcDataSourceProviderTest.java
- langstream-agents/langstream-vector-agents/pom.xml
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/QueryVectorDBAgent.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/jdbc/JdbcWriter.java
- langstream-agents/langstream-vector-agents/src/main/resources/META-INF/services/ai.langstream.api.database.VectorDatabaseWriterProvider
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/JdbcWriterTest.java
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/PineconeDataSourceTest.java
Summary:
- add support for writing to SQL database in the "vector-db-sink" agent
- we are going to use HerdDB embedded database for the unit tests, as it will support Vector search in the next 0.28.0 release (coming soon), the test is currently disable, we can enable it as soon as the new release is out
- please note that we are not importing any third party JDBC Driver (it is only a test dependency) in the docker images
> [vector-db-sink] Implement support for writing to JDBC services

- langstream-core/src/main/java/ai/langstream/impl/agents/ai/GenAIToolKitFunctionAgentProvider.java
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
- langstream-core/src/main/java/ai/langstream/impl/resources/AIProvidersResourceProvider.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/TextCompletionsIT.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/util/BaseEndToEndTest.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/util/kafka/RemoteKafkaProvider.java
- langstream-e2e-tests/src/test/resources/apps/text-completions/configuration.yaml
- langstream-e2e-tests/src/test/resources/apps/text-completions/pipeline.yaml
- langstream-e2e-tests/src/test/resources/secrets/secret1.yaml
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/GenAIAgentsTest.java
Currently if you configure both open-ai and vertex-ai as AI resources, the AI Agent will use the first one loaded at runtime. 
Changes:
* Added support for specifying the service type using `ai-service: x` where x must match a provider id/name
Example:
```yaml
configuration:
resources:
- name: open-ai
type: open-ai-configuration
configuration:
url: "http://something"
access-key: "xxcxcxc"
provider: "azure"
- name: my-vertex
type: vertex-configuration
configuration:
url: "http://something"
token: xx
project: yy
```
```yaml
module: "module-1"
id: "pipeline-1"
topics:
- name: "input-topic"
- name: "output-topic"
pipeline:
- name: "compute-embeddings"
id: "step1"
type: "compute-ai-embeddings"
input: "input-topic"
output: …
```
> Allow to configure more than one AI service

- dev/start-local.sh
- examples/applications/docker-chatbot/configuration.yaml
- examples/secrets/secrets.yaml
- helm/examples/herddb-dev.yaml
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
Summary:
- add a simple YAML K8S manifest  similar to the Minio manifest to start a single pod HerdDB service
- change the secrets file to use the K8S name for HerdDB
- register the same name as an alias for localhost, like we do for Kafka and Minio, in "docker-run" mode
> [local mode] Add examples about how to deploy HerdDB in minikube

- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/apps/AppResourcesFactory.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/apps/AppResourcesFactoryTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/AppControllerIT.java
- langstream-runtime/langstream-runtime-api/src/main/java/ai/langstream/runtime/api/application/ApplicationSetupConfiguration.java
- langstream-runtime/langstream-runtime-api/src/main/java/ai/langstream/runtime/api/application/ApplicationSetupConstants.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/application/ApplicationSetupRunnerStarter.java
Follow up of #490 
The setup job loads the application code and use it during the assets creation if needed. 
This unblocks the Postgres example to use the assets
> Load app code in the setup job

- examples/applications/docker-chatbot/configuration.yaml
- examples/applications/docker-chatbot/crawler.yaml
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
- langstream-core/src/test/java/ai/langstream/impl/parser/ModelBuilderTest.java
- langstream-core/src/test/resources/application1/configuration.yaml
Summary:
With this new feature you can define the default values of the "global variables" in the configuration.yaml,
this is very handy because now you don't need to use special instance.yaml files when you are using global variables.
Global variables are useful when you want to make your application parametric, but as soon as you start using them you need to craft dedicated instance.yaml files otherwise your application won't work.
Example for this new feature:
configuration.yaml
```yaml
configuration:
defaults:
globals:
website: https://langstream.ai
resources:
...
```
instance.yaml
```yaml
instance:
globals:
website: https://langstream.ai
```
> [apps] Allow to specify default values for globals in configuration.yaml

- langstream-core/src/main/java/ai/langstream/impl/common/ApplicationPlaceholderResolver.java
- langstream-core/src/test/java/ai/langstream/impl/common/ApplicationPlaceholderResolverTest.java
Summary:
with #507 old applications that use secrets (so 100% of them) require to be rewritten, it is better to not require it.
This patch adds a small backward compatibility layer that allows to interpret secrets and globals using the Mustache syntax.
Please note that when you use Mustache the result is always a string, so if you have a number or a list, you will see them returned as strings.
The suggested way to refer to a secret is now ${secrets.id.field} and ${globals.variable}
> [compatibility] Backward compatibility with references to secrets and globals using the Mustache syntax

- langstream-cli/pom.xml
We can include the generated .bat file in the zip. 
I tested it on windows 11 with java 11 and it works like a charm.
The only problem is that windows users will have to download the tarball, extract it and run it. There's no global command
> Cli: include .bat file in the tarball

- langstream-agents/langstream-agents-commons/src/main/java/ai/langstream/ai/agents/commons/TransformContext.java
- langstream-agents/langstream-agents-flow-control/pom.xml
- langstream-agents/langstream-agents-flow-control/src/main/java/ai/langstream/agents/flow/DispatchAgent.java
- langstream-agents/langstream-agents-flow-control/src/main/java/ai/langstream/agents/flow/FlowControlAgentsCodeProvider.java
- langstream-agents/langstream-agents-flow-control/src/main/resources/META-INF/ai.langstream.agents.index
- langstream-agents/langstream-agents-flow-control/src/main/resources/META-INF/services/ai.langstream.api.runner.code.AgentCodeProvider
- langstream-agents/langstream-agents-flow-control/src/test/resources/logback-test.xml
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/GenAIToolKitAgent.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/rerank/ReRankAgent.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/CastStep.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/util/TransformFunctionUtil.java
- langstream-agents/langstream-ai-agents/src/test/java/com/datastax/oss/pulsar/functions/transforms/TransformFunction.java
- langstream-agents/langstream-ai-agents/src/test/java/com/datastax/oss/streaming/ai/Utils.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/QueryVectorDBAgent.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/jdbc/JdbcWriter.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/milvus/MilvusWriter.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/pinecone/PineconeWriter.java
- langstream-agents/pom.xml
- langstream-api/src/main/java/ai/langstream/api/runner/topics/TopicConnectionProvider.java
- langstream-api/src/main/java/ai/langstream/api/util/ConfigurationUtils.java
- langstream-core/src/main/java/ai/langstream/impl/uti/ClassConfigValidator.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/FlowControlAgentsProvider.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/resources/META-INF/services/ai.langstream.api.runtime.AgentNodeProvider
- langstream-kafka-runtime/src/main/java/ai/langstream/kafka/runner/kafkaconnect/KafkaConnectSourceAgent.java
- langstream-runtime/langstream-runtime-impl/pom.xml
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/FlowControlRunnerIT.java
Fixes #454
Summary:
- this patch adds a new processor 'dispatch' that is able to dispatch the record to different topics depending on a condition
This is an example:
```
topics:
- name: "input-topic"
- name: "topic1"
- name: "topic2"
- name: "default-topic"
pipeline:
- name: "Dispatch"
type: "dispatch"
input: input-topic
output: default-topic
id: step1
configuration:
routes:
- when: properties.language == "en"
destination: topic1
- when: properties.language == "fr"
destination: topic2
action: dispatch
- when: properties.language == "none"
action: drop
```
Important notes:
- the routes are evaluated in order, as soon as one condition is verified …
> [agents] New agent 'dispatch' for message routing

- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/model/Applications.java
- langstream-api/src/main/java/ai/langstream/api/webservice/application/ApplicationDescription.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/BaseCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/AppsCmdTest.java
- langstream-runtime/langstream-runtime-tester/src/main/assemble/entrypoint.sh
- langstream-runtime/langstream-runtime-tester/src/main/docker/Dockerfile
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/Main.java
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationResource.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/AppTestHelper.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/ApplicationResourceTest.java
Fixes #532
Changes:
* New option in the deploy `langstream apps deploy --dry-run my-app -app ...`. This sends a request to the control plane.
* The control plane handles the new option and generates the application description with the resolved application. The app is not deployed
* You can customize the output with `-o yaml/json`. By default is `yaml`
* The same option is not recognized for the update command since we don't want to expose already stored secrets to the user (that might not have access to them)
> Add dry-run apps deployment

- examples/applications/http-request-processor/README.md
- examples/applications/http-request-processor/gateways.yaml
- examples/applications/http-request-processor/pipeline.yaml
- langstream-agents/langstream-agent-http-request/pom.xml
- langstream-agents/langstream-agent-http-request/src/main/java/ai/langstream/agents/queryhttp/HttpRequestAgent.java
- langstream-agents/langstream-agent-http-request/src/main/java/ai/langstream/agents/queryhttp/HttpRequestAgentProvider.java
- langstream-agents/langstream-agent-http-request/src/main/resources/META-INF/ai.langstream.agents.index
- langstream-agents/langstream-agent-http-request/src/main/resources/META-INF/services/ai.langstream.api.runner.code.AgentCodeProvider
- langstream-agents/pom.xml
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/HttpRequestAgentProvider.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/resources/META-INF/services/ai.langstream.api.runtime.AgentNodeProvider
- langstream-runtime/langstream-runtime-impl/pom.xml
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/CassandraAssetQueryWriteIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/CassandraVectorAssetQueryWriteIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/HttpRequestAgentRunnerIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/mockagents/MockAssetManagerCodeProvider.java
* Added new `http-request` agent
* It accepts
* url: http(s) url to call without query-string
* query-string (map): accepts string as template. encoding is done automatically
* method: "get" by default
* headers (map):  accepts string as template e.g. X-Custom-Header: {{{ value.id }}}
* body: body to send, must be a string:  accepts string as template e.g. X-Custom-Header: {{{ value.id }}}
* output-field: field where to output in the record. in case the response return content-type: application/json it will be deserialized as map. otherwise will be threated as string 
* allow-redirects: set to false to never redirect
* handle-cookies: set to false to not manage cookies during redirects
Example with authentication
```
- name: "http-request"
type: "http-request"
input: input-topic
output: …
```
> New http-request agent

- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawler.java
> Fix WebCrawler handle-cookies option

- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/model/Applications.java
- langstream-api/src/main/java/ai/langstream/api/storage/ApplicationStore.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/GetApplicationLogsCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/UIAppCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/AppsCmdTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/util/KubeUtil.java
- langstream-k8s-storage/src/main/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStore.java
- langstream-k8s-storage/src/test/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStoreLogsTest.java
- langstream-runtime/langstream-runtime-base-docker-image/src/main/docker/Dockerfile
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationResource.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/ApplicationResourceLogsTest.java
Fixes: #453
Changes:
* Better handling of logs in case the pod is in crash loop. We also check the pod status before asking for the logs. In case it's not running we show the error message and sleep 10 seconds and retry
* Added new query string param "format=json|text" to get the result in NDJSON format containing "message", "replica", "timestamp". For the CLI, `apps logs <app> -o json`
> Improve apps logs command for CrashLoopBack and add JSON format

- langstream-k8s-deployer/langstream-k8s-deployer-api/pom.xml
- pom.xml
Current jandex plugin generates a different jandex file each time, preventing the java compiler to use the incremental compilation.
Also the jboss plugin is deprecated
> Upgrade jandex maven plugin

- examples/applications/chatbot-rag-memory/README.md
- examples/applications/chatbot-rag-memory/chatbot.yaml
- examples/applications/chatbot-rag-memory/configuration.yaml
- examples/applications/chatbot-rag-memory/crawler.yaml
- examples/applications/chatbot-rag-memory/gateways.yaml
- examples/applications/chatbot-rag-memory/write-to-astra.yaml
Updates to chatbot-rag-memory example:
* Small tweaks to support the 0.1.0 release
* Switch globals to new variable format
* Switch mustache templating to new format
* Add defaults for globals in configuration.yaml
> Update variable format for chatbot-rag-memory example

- langstream-pulsar-runtime/pom.xml
- pom.xml
NB: this makes Pulsar not working anymore with Avro manipulating agents. But without this Pulsar doesn't work at all.
We can fix the problem with Avro later.
> Fix pulsar runtime depency conflicts

- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/UIAppCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/UIAppCmdTest.java
Fix this bad stacktrace
```
/langstream-agents-text-processing-0.2.0-nar.nar to /tmp/nar281146335772970230/langstream-agents-text-processing-0.2.0-nar.nar.dir
Exception in thread "pool-2-thread-1" java.io.IOException: Cannot run program "open": error=2, No such file or directory
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at ai.langstream.cli.commands.applications.UIAppCmd.startServer(UIAppCmd.java:168)
at ai.langstream.cli.commands.docker.LocalRunApplicationCmd.startUI(LocalRunApplicationCmd.java:385)
at ai.langstream.cli.commands.docker.LocalRunApplicationCmd.lambda$executeOnDocker$2(LocalRunApplicationCmd.java:348)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecu …
```
> CLI UI: do not print stacktrace if 'open' command is not available

- langstream-cli/src/main/resources/app-ui/index.html
Adding a feature that I have wanted ever since we introduced the logs API--a way to filter the log responses by severity. This is pretty easy to do in the UI.
The filter looks like this:
It is not super strict, so sometimes it will show lines that are not at the log level, for example when the API returns multiple lines at a time. If at least one of the logs matches, they will all be displayed. However, I think this limitation is good enough for now.
> Add severity filter for logs to UI

- langstream-core/src/main/java/ai/langstream/impl/agents/ai/GenAIToolKitFunctionAgentProvider.java
- langstream-core/src/main/java/ai/langstream/impl/uti/ClassConfigValidator.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/agents/AgentValidationTestUtil.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/agents/KubernetesGenAIToolKitFunctionAgentProviderTest.java
Fixes https://github.com/LangStream/langstream/issues/595
The control plane should validate and provide meaningful message when the ai service cannot be found
> Improve missing AI service validation

- conf/cli.yaml
- examples/applications/openai-completions/gateways.yaml
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/BaseDockerCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-cli/src/main/resources/app-ui/index.html
- langstream-cli/src/test/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmdTest.java
Changes: 
* use "default" as mock tenant, this is likely to match the default profile when then running gateway commands
* creates/updates a profile named "local-docker-run" that points to the right tenant/urls
* Render markdown is checked by default
> CLI docker run: create a dedicated profile  

- langstream-runtime/langstream-runtime-base-docker-image/src/main/docker/Dockerfile
- langstream-runtime/langstream-runtime-impl/src/main/python/Pipfile
- langstream-runtime/langstream-runtime-impl/src/main/python/Pipfile.lock
- langstream-runtime/langstream-runtime-impl/src/main/python/README.md
Partial revert of: https://github.com/LangStream/langstream/pull/539
basically the ecosystem of "unstructred" plugins is ~6G so we cannot really use all of them
> Fix runtime image size

- examples/applications/query-postgresql-chat-history/README.md
- langstream-runtime/langstream-runtime-tester/pom.xml
- langstream-runtime/langstream-runtime-tester/src/main/assemble/entrypoint.sh
- langstream-runtime/langstream-runtime-tester/src/main/assemble/logback.xml
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/CompletionWaiter.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/InMemoryApplicationStore.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/LocalApplicationRunner.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/Main.java
- langstream-runtime/langstream-runtime-tester/src/test/java/tests/CompletionWaiterTest.java
Summary:
- ensure that we exit the container in case of any errors: during setup and in case of any agent failure
- reduce some logs
- ensure that logback configuration is applied
> [docker run] Exit the container in case of errors

- examples/applications/query-opensearch/configuration.yaml
- examples/applications/query-opensearch/query.yaml
- examples/applications/query-opensearch/write.yaml
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/opensearch/OpenSearchAssetsManagerProvider.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/opensearch/OpenSearchDataSource.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/opensearch/OpenSearchWriter.java
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/OpenSearchDataSourceTest.java
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/opensearch/OpenSearchDataSourceTest.java
- langstream-core/src/main/java/ai/langstream/impl/assets/OpenSearchAssetsProvider.java
- langstream-core/src/main/java/ai/langstream/impl/resources/datasource/OpenSearchDatasourceConfig.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/vectors/OpenSearchVectorDatabaseWriterConfig.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/agents/QueryVectorDBAgentProviderTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/OpenSearchVectorIT.java
Currently the query can't be filtered by index and that is very problematic. The only solution that makes sense for the query agent is that the index is defined in the datasource itself. this also helps assets and writer to not need the index declared twice.
This change adds the "index-name" to the opensearch config and removes it from asset and vector-db-sink.
With this, you cannot perform query to multiple indices but it's fine
> Move OpenSearch configuration to use a single index

- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/QueryStep.java
- langstream-agents/langstream-ai-agents/src/test/java/com/datastax/oss/streaming/ai/QueryStepTest.java
This PR tries to reproduce issue #581 
Actually it doesn't reproduce the problem, probably the problem has been already fixed.
Closes #581
> [query agent] Add test case with output-field that contains a dash character

- conf/cli.yaml
- langstream-cli/src/main/java/ai/langstream/cli/CLILogger.java
- langstream-cli/src/main/java/ai/langstream/cli/LangStreamCLI.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/BaseCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/GithubRepositoryDownloader.java
- langstream-cli/src/main/java/ai/langstream/cli/util/GitClient.java
- langstream-cli/src/main/java/ai/langstream/cli/util/git/JGitClient.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmdTest.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/GithubRepositoryDownloaderTest.java
Currently every time the user specify a github repository for the application/secrets/instance we clone the entire git repository N times. If the user submit the deploy again, the repo is cloned from sctratch again. 99% of use cases are to download from this repo and it takes up to 10 seconds. 
Changes:
* Save git repository clone in ~/.langstream/ghrepos with the repo identifier. If the repo specified already exists, we just reset and fetch to the specified branch. **This is much faster than cloning the repo: ~3-4s vs 10~12s on my machine**
* In case the same command specify the same repository, the second one will be considered up to date and nothing will be done (neither clone or fetch)
* Added `--disable-local-repositories-cache` to fallback to the old behaviour
* In case of failures, …
> CLI: cache github repository for faster deployments

- bin/get-cli.sh
- conf/cli.yaml
- langstream-cli/src/main/java/ai/langstream/cli/LangStreamCLI.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/BaseCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmdTest.java
- langstream-runtime/langstream-runtime-tester/src/main/docker/Dockerfile
Changes: 
* Set generated files readable for every user to avoid permissions error. The files are copied to $HOME/.langstream/tmp directory which is protected to other unix machine users but still readable from the container
* Improve the installation script error message
After these changes, I successfully setup an amazon linux machine to run langstream (I'll add it to the doc):
```
sudo yum update
sudo yum install -y docker jq unzip  java-11-amazon-corretto-headless
sudo usermod -a -G docker ec2-user
id ec2-user
newgrp docker
sudo systemctl enable docker.service
sudo systemctl start docker.service
curl -Ls "https://raw.githubusercontent.com/LangStream/langstream/main/bin/get-cli.sh" | bash
source ~/.bashrc
export OPEN_AI_ACCESS_KEY=your-key-here
langstream docker run test -app …
```
> Cli: fix docker run on linux

- conf/cli.yaml
- examples/applications/docker-chatbot/crawler.yaml
- examples/applications/query-postgresql-chat-history/clean-history.yaml
- examples/applications/webcrawler-source/write-to-astra.yaml
- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerStatus.java
- langstream-agents/langstream-agents-commons/src/main/java/ai/langstream/ai/agents/commons/jstl/JstlEvaluator.java
- langstream-agents/langstream-agents-commons/src/main/java/ai/langstream/ai/agents/commons/jstl/JstlFunctions.java
- langstream-agents/langstream-agents-flow-control/src/main/java/ai/langstream/agents/flow/FlowControlAgentsCodeProvider.java
- langstream-agents/langstream-agents-flow-control/src/main/java/ai/langstream/agents/flow/LogEventProcessor.java
- langstream-agents/langstream-agents-flow-control/src/main/java/ai/langstream/agents/flow/TimerSource.java
- langstream-agents/langstream-agents-flow-control/src/main/resources/META-INF/ai.langstream.agents.index
- langstream-agents/langstream-agents-flow-control/src/test/java/ai/langstream/agents/flow/FlowControlAgentsTest.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/datasource/CassandraDataSource.java
- langstream-core/src/main/java/ai/langstream/impl/agents/ai/steps/ComputeConfiguration.java
- langstream-core/src/main/java/ai/langstream/impl/agents/ai/steps/QueryConfiguration.java
- langstream-core/src/main/java/ai/langstream/impl/uti/ClassConfigValidator.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/FlowControlAgentsProvider.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/agents/KubernetesGenAIToolKitFunctionAgentProviderTest.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/agents/QueryVectorDBAgentProviderTest.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/SourceRecordTracker.java
Summary:
- add new EL function fn:toSQLTimestamp to work with SQL databases (like PostGRE)
- add automatic purge of the chat history in the PostgreSQL chat history example application
- add automatic deletion of stale chunks in the webcrawler and the docker-chatbot example applications
- reduce logging
- add a new "log-event" agent, that allows you to write to the log in order to debug what's happening in the pipeline
> Enhance the example applications: chat history and webcrawler (and add the 'log-event' agent)

- conf/cli.yaml
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmdTest.java
After the recent changes on 0.3.0, the temporary directory containing the application is only readable (not executable). UNIX permissions require the "execute" permission on a directory to perform listing
Since on Mac copying the app directory is not needed, we only perform the copy on linux
> CLI: fix temp file permissions

- .github/workflows/release.yml
- .github/workflows/test-cli-macos.yml
- dev/cli-post-release-tests.sh
* After the release we run a test that
* Run brew install to get the CLI
* It verifies the expected version
* It runs a e2e test with the downloaded binary
> Add post-release test for brew and CLI

- examples/applications/slack/README.md
- examples/applications/slack/configuration.yaml
- examples/applications/slack/gateways.yaml
- examples/applications/slack/pipeline.yaml
- examples/secrets/secrets.yaml
Just couldn't figure out how to incorporate variables.  Looked at the documentation, but not enough there.  Will need to look at the code for answers. Everything is in langstream/examples/applications/slack.  README.md contains commands I used to start langstream and send a request.
> Add example application about how to write to Slack using the http-request agent

- examples/applications/langchain-chat/.langstreamignore
- examples/applications/langchain-chat/README.md
- examples/applications/langchain-chat/configuration.yaml
- examples/applications/langchain-chat/crawler.yaml
- examples/applications/langchain-chat/gateways.yaml
- examples/applications/langchain-chat/pipeline.yaml
- examples/applications/langchain-chat/python/langchain_chat.py
- examples/applications/python-processor-embeddings/README.md
- examples/secrets/secrets.yaml
This is the first iteration of the sample application about how to build a chat bot using LangChain and the RAG pattern.
Summary:
- the code is inspired by https://github.com/langchain-ai/chat-langchain
- the application uses DataStax Astra DB as vector database
- OpenAI is used as LLM for completions and for computing the text embeddings
- as in the original chat application, the chat history is to be handled on the client side
> [examples] Add a chatbot built with LangChain and Astra DB

- examples/applications/langchain-chat/pipeline.yaml
- examples/applications/langchain-chat/python/langchain_chat.py
- examples/secrets/secrets.yaml
Summary:
- add to the chatbot sample with LangChain the ability to configure the connection to LangSmith
- add default "secrets" to read from the ENV the variables to connect to LangSmith
> Add sample integration with LangSmith

- .github/workflows/ci.yml
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/PythonGrpcAgentProcessor.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/PythonGrpcAgentSink.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/PythonGrpcAgentSource.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/PythonGrpcServer.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/util/BaseEndToEndTest.java
- langstream-e2e-tests/src/test/resources/apps/python-processor/pipeline.yaml
- langstream-e2e-tests/src/test/resources/apps/python-processor/python/example.py
- langstream-runtime/langstream-runtime-impl/src/main/python/Pipfile
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream/__init__.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream/api.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/__main__.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/api.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/grpc_service.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/server_and_stub.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/test_grpc_processor.py
Changes:
- Added new Python AgentContext class to the API
- An agent can access it by defining
```
from langstream import SimpleRecord, Processor, AgentContext
import logging, os
class Exclamation(Processor):
def init(self, config, context: AgentContext):
self.context = context
def process(self, record):
directory = self.context.get_persistent_state_directory() 
``` 
if the agent declares init with only argument, it works as before
- Added end to end test
> Add persistent state directory to python agents

- examples/applications/python-processor-exclamation/README.md
- examples/applications/python-processor-exclamation/python/requirements.txt
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootPythonCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/python/BasePythonCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/python/LoadPythonDependenciesCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/util/DockerImageUtils.java
Summary:
This path adds a new CLI command to process the requrements.txt file using the same version of the OS and of Python that run in production, on Linux/Intel.
This is very useful in order to ensure that the dependencies that you import match correctly the production enviroment
`langstream python load-pip-requirements -app examples/applications/python-processor-exclamation`
> [python] Add a CLI command to import pip requirements.txt

- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/cassandra/CassandraWriter.java
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream/api.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/api.py
Summary:
- use ConfigurationUtils.getString to handle missing entries as well as null values
- for Astra use PROD as default environment, it was set to DEV by mistake
> [cassandra] Handle errors due to missing parameters

- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/AbstractGrpcAgent.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/GrpcAgentProcessor.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/PythonGrpcAgentProcessor.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/PythonGrpcAgentSink.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/PythonGrpcAgentSource.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/PythonGrpcServer.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentCode.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentCodeAndLoader.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/ApplicationWatcher.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmdTest.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunnerStarter.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/CompositeAgentProcessor.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/api/AgentAPIController.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/api/AgentInfoServlet.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/AbstractKafkaApplicationRunner.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/InMemoryApplicationStore.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/LocalApplicationRunner.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/Main.java
Summary:
When you are working locally, add the ability to automatically reload python code without restarting the container
In "docker run" mode the cli start watching on the python files.
In case of any python file that has changed the python agent is restarted, picking up the new version of the code.
The is a new flag "--watch-files=false" to disable the feature.
The watcher starts only if there is a "python" directory in the application
Follow up:
- if there is a syntax error the Python process crashes, so the docker container exists
- add test cases
> [python] Add support for hot reload of python code in docker mode

- langstream-core/src/main/java/ai/langstream/impl/nar/NarFileHandler.java
- langstream-runtime/langstream-runtime-tester/src/main/assemble/entrypoint.sh
When the docker container is existing, usually due to an error in the configuration, we close the classloaders and this triggers a lot of spammy ClassNotFound errors that are misleading, because users think that there is a bug somewhere in LangStream.
The trick here is not not close them: the JMV is existing, there is no risk of leaking resources.
Also the tmp directory of the container is ephemeral: we are not leaving dangling temporary files
> [docker] Do not close classloaders, to prevent spammy ClassNotFoundExceptions

- langstream-api-gateway-auth/langstream-google-api-gateway-auth/src/main/java/ai/langstream/apigateway/auth/impl/google/GoogleAuthenticationProvider.java
- langstream-api-gateway-auth/langstream-http-api-gateway-auth/src/main/java/ai/langstream/apigateway/auth/impl/jwt/admin/HttpAuthenticationProvider.java
- langstream-api-gateway-auth/langstream-jwt-api-gateway-auth/src/main/java/ai/langstream/apigateway/auth/impl/jwt/admin/JwtAuthenticationProvider.java
- langstream-api-gateway/pom.xml
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/ConsumeGateway.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/GatewayRequestHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/GatewayRequestHandlerFactory.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/ProduceGateway.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/http/GatewayResource.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/http/ResourceErrorsHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/util/HttpUtil.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/AuthenticationInterceptor.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/WebSocketConfig.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/AbstractHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ChatHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ConsumeHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ProduceHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/impl/AuthenticatedGatewayRequestContextImpl.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/http/GatewayResourceTest.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/http/KafkaGatewayResourceTest.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/http/PulsarGatewayResourceTest.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/websocket/TestGatewayAuthenticationProvider.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/websocket/handlers/ProduceConsumeHandlerTest.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/BaseGatewayCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/ChatGatewayCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/ConsumeGatewayCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/gateway/ProduceGatewayCmd.java
- langstream-kafka-runtime/pom.xml
- langstream-pulsar-runtime/pom.xml
- langstream-pulsar-runtime/src/main/java/ai/langstream/pulsar/runner/PulsarTopicConnectionsRuntimeProvider.java
Changes:
* It is now possible produce a message for a "produce" gateway by using HTTP. There's no need to change anything in the application config.
* The endpoint is http://api-gateway-xxxx:8091/api/gateways/produce/{tenant}/{application}/{gateway}
The body must be a json {value: xx, key:xx, headers: {xx}}
> Gateway: accept HTTP request for producing messages

- langstream-runtime/langstream-runtime-impl/src/main/assemble/entrypoint.sh
After the upgrade to OpenJDK in kubernetes I see this error.
The fix is to apply this system property -Djdk.lang.Process.launchMechanism=vfork
Please note that we were already using that flag in the langstream docker tester docker image (for docker run)
```
java.io.IOException: Cannot run program "python3": error=0, Failed to exec spawn helper: pid: 31, exit value: 1                                  │
│ runtime     at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)                                                                        │
│ runtime     at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)                                                                        │
│ runtime     at ai.langstream.agents.grpc.PythonGrpcServer.start(PythonGrpcServe …
```
> [python] use vfork to start the python interpreter (needed for openjdk)

- langstream-e2e-tests/src/test/java/ai/langstream/tests/util/kafka/LocalRedPandaClusterProvider.java
CI is failing due to a problem in the RedPanda helm chart
```
15:25:19.268 [ForkJoinPool.commonPool-worker-1] INFO  a.l.t.u.k.LocalRedPandaClusterProvider -- running helm command to install redpanda
[455](https://github.com/LangStream/langstream/actions/runs/6669026801/job/18125905752?pr=661#step:9:456)
Error: template: redpanda/templates/post-upgrade.yaml:78:40: executing “redpanda/templates/post-upgrade.yaml” at <eq (floor $value) $value>: error calling eq: incompatible types for comparison
```
This patch is trying to rollback to an older version that was known to work
> [tests] Use a fixed version of RedPanda that is known to work

- langstream-api-gateway/pom.xml
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/LangStreamApiGateway.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/MetricsNames.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/config/TopicProperties.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/ConsumeGateway.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/LRUTopicProducerCache.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/ProduceGateway.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/TopicProducerCache.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/TopicProducerCacheFactory.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/http/GatewayResource.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/WebSocketConfig.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/AbstractHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ChatHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ConsumeHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ProduceHandler.java
- langstream-api-gateway/src/main/resources/application.properties
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/gateways/LRUTopicProducerCacheTest.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/http/GatewayResourceTest.java
- langstream-api-gateway/src/test/resources/application.properties
Changes:
* We use Guava cache to keep producer by gateway. The cache is LRU and every access refresh the ttl. 
* The max size is configurable (max 100 across all tenants). The cache can be disabled
> API gateway: cache topic producer for the same gateway

- conf/cli.yaml
- langstream-cli/pom.xml
- langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/python/LoadPythonDependenciesCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/util/DockerImageUtils.java
Changes:
* Added possibility add an ENV file that is loaded before the actual java command. the file must be in the bin directory and must be named `langstream.env`
* Docker image by default is retrieved from LANGSTREAM_RUNTIME_DOCKER_IMAGE env
> CLI: add .env configuration file

- examples/applications/python/langserve-service/gateways.yaml
- examples/applications/python/langserve-service/pipeline.yaml
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/GatewayRequestHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/http/GatewayResource.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/http/GatewayResourceTest.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/http/ServiceAgentGatewayResourceTest.java
- langstream-api/src/main/java/ai/langstream/api/model/Gateway.java
- langstream-api/src/main/java/ai/langstream/api/storage/ApplicationStore.java
- langstream-core/src/main/java/ai/langstream/impl/parser/ModelBuilder.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/util/KubeUtil.java
- langstream-k8s-storage/src/main/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStore.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/InMemoryApplicationStore.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/ApplicationServiceResourceLimitTest.java
Changes:
* Added support for gateway 'service' that instead of specifying output and input topic, you can specify an agent-id. The agent must be of type the new type 'service'
* The requests are forwarded including query string and headers. POST, PUT, DELETE, GET methods are all supported
> Service gateway: direct interaction with agent

- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/WebCrawlerSourceAgentProvider.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/agents/WebCrawlerSourceAgentProviderTest.java
Error (only on main branch)
```
Cannot invoke \"String.equals(Object)\" because \"stateStorage\" is null
```
> Fix WebCrawler state-storage default value

- examples/applications/slack/README.md
correct misspelling in README.md
> [examples] correct misspelling in README.md

- langstream-cli/src/main/java/ai/langstream/cli/commands/python/BasePythonCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/python/LoadPythonDependenciesCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/python/PythonRunTests.java
Summary:
add a new command
`langstream python run-tests -app /path/to/application
`
This runs "python3 -m unittest" by default, but you can customized the command
`langstream python run-tests -app /path/to/application -c "tox"`
> [python] Add CLI command to run tests

- langstream-agents/langstream-agent-http-request/src/main/java/ai/langstream/agents/http/LangServeClient.java
- langstream-agents/langstream-agent-http-request/src/main/java/ai/langstream/agents/http/LangServeInvokeAgent.java
- langstream-agents/langstream-agent-http-request/src/test/java/ai/langstream/agents/http/LangServeInvokeAgentTest.java
Summary:
- handle String content
- extract the code of the Java LangServeClient
- add tests
> [langserve-invoke] Extract the LangServe Java Client code and Allow to parse simple strings and not only JSON

- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/GenAIToolKitAgent.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/services/ServiceProviderRegistry.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/services/impl/BedrockServiceProvider.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/services/impl/HuggingFaceProvider.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/services/impl/OpenAIServiceProvider.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/services/impl/VertexAIProvider.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/embeddings/EmbeddingServiceResponse.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/embeddings/OpenAIEmbeddingsService.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/services/OpenAIServiceProvider.java
- langstream-agents/langstream-ai-agents/src/test/java/ai/langstream/ai/agents/GenAIToolKitAgentTest.java
- langstream-agents/langstream-ai-agents/src/test/java/ai/langstream/ai/agents/services/impl/HuggingAIProviderTest.java
- langstream-agents/langstream-ai-agents/src/test/java/ai/langstream/ai/agents/services/impl/OpenAIProviderTest.java
- langstream-agents/langstream-ai-agents/src/test/java/ai/langstream/ai/agents/services/impl/VertexAIProviderTest.java
- langstream-agents/langstream-ai-agents/src/test/java/com/datastax/oss/pulsar/functions/transforms/GenAITest.java
- langstream-agents/langstream-ai-agents/src/test/java/com/datastax/oss/pulsar/functions/transforms/TransformFunction.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/AgentContext.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/MetricsReporter.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/metrics/PrometheusMetricsReporter.java
Summary:
- add support for Java agents to push metrics to Prometheus
- implement basic metrics for OpenAI consumptions for the Embeddings service
> [agents] Add support for exporting custom metrics to Prometheus

- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/ConsumeGateway.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/ProduceGateway.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/http/GatewayResource.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/http/ResourceErrorsHandler.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/http/GatewayResourceTest.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/websocket/handlers/ProduceConsumeHandlerTest.java
- langstream-pulsar-runtime/src/main/java/ai/langstream/pravega/runner/PulsarTopicConnectionsRuntimeProvider.java
Changes:
* Invert input and output topic as expected
* add fixed header `langstream-service-request-id` to ensure getting the response to the previously sent message
* Http gateways now by default expects a plain/text that will be part the message value. By passing Content-Type application/json you can still pass the entire body 
* improved tests
> Fix service gateway with topics

- langstream-agents/langstream-agents-commons/src/main/java/ai/langstream/ai/agents/commons/jstl/JstlEvaluator.java
- langstream-agents/langstream-agents-commons/src/main/java/ai/langstream/ai/agents/commons/jstl/JstlFunctions.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/ComputeStep.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/model/ComputeFieldType.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/cassandra/CassandraWriter.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/CassandraVectorAssetQueryWriteIT.java
Summary:
- add mapOf(...), listOf(...), concat(....),mapAll(), mapRemove() EL functions
- add integration test about how to deal with map<string, string> objects in Cassandra, that is used by Cass.io
```yaml
pipeline:
- id: step1
type: compute
name: "Compute metadata"
input: "input-topic-cassio"
configuration:
fields:
- name: "value.metadata_s"
expression: "fn:mapOf('filename', value.filename, 'chunk_id', value.chunk_id)"
- name: "Write a new record to Cassandra"
type: "vector-db-sink"
configuration:
datasource: "CassandraDatasource"
table-name: "documents"
keyspace: "cassio"
mapping: "row_id=value.row_id,attributes_blob=value.attributes_blob,body_blob=value.body_blob,metadata_s=value.metadata_s,vector=value.vector"
```
> Add examples and utility function to deal with Cassio

- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/model/Applications.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/RootArchetypeCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/archetypes/CreateAppFromArchetypeCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/archetypes/GetArchetypeCmd.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/archetypes/ListArchetypesCmd.java
- langstream-webservice/src/main/docker/jib/app/archetypes/website-qa-chatbot/secrets.yaml
- langstream-webservice/src/test/website-qa-chatbot-parameters-example.json
Summary:
- add langstream archetypes get command
- add langstream archetypes create-application command
- fix the sample archetype (default values of secrets cannot be read from the ENV, as the deploy application command basically runs on the control plane and not locally)
- add a sample JSON file with the parameters corresponding to the demo archetype bundled with LangStream
> [cli] Add Commands to create an application from an archetype

- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/grpc_service.py
Since environment variables often contain secrets, we should not log them at INFO level.
> Change log level for Python environnment variables

- examples/applications/langchain-chat/configuration.yaml
- examples/applications/langchain-chat/crawler.yaml
- examples/applications/langchain-chat/pipeline.yaml
- examples/applications/langchain-chat/python/langchain_chat.py
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/datasource/CassandraDataSource.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/cassandra/CassandraWriter.java
- langstream-core/src/main/java/ai/langstream/impl/resources/datasource/AstraDatasourceConfig.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/PythonCodeAgentProvider.java
Summary:
- in python agents LangStream is now passing all the "Resources" to the configuration of the agent
- add support for using database-id in AstraDB datasources
With this change you can declare the access to DataSources/Vector Database and to AI service providers only once in your application, then in Python you can use the values.
This way there is no need to add boilerplate to map the access keys in the pipeline files.
In python now you can access resources and globals:
- config["resources"]
- config["globals"]
> [python agents] Allow to access resources configured in configuration.yaml

- docker/metrics/dashboards/apps.json
- langstream-agents/langstream-agent-camel/src/test/java/ai/langstream/agents/camel/CamelSourceTest.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/AbstractGrpcAgent.java
- langstream-agents/langstream-agent-http-request/src/main/java/ai/langstream/agents/http/HttpRequestAgent.java
- langstream-agents/langstream-agent-http-request/src/main/java/ai/langstream/agents/http/LangServeInvokeAgent.java
- langstream-agents/langstream-agent-s3/src/test/java/ai/langstream/agents/s3/S3SourceTest.java
- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/WebCrawlerSource.java
- langstream-agents/langstream-agents-flow-control/src/main/java/ai/langstream/agents/flow/DispatchAgent.java
- langstream-agents/langstream-agents-flow-control/src/main/java/ai/langstream/agents/flow/TriggerEventProcessor.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/GenAIToolKitAgent.java
- langstream-agents/langstream-ai-agents/src/main/java/ai/langstream/ai/agents/flare/FlareControllerAgent.java
- langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/VectorDBSinkAgent.java
- langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/CassandraWriterTest.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/AbstractAgentCode.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/MetricsReporter.java
- langstream-api/src/main/java/ai/langstream/api/runner/code/SimpleCounter.java
- langstream-kafka-runtime/src/main/java/ai/langstream/kafka/runner/kafkaconnect/KafkaConnectSinkAgent.java
- langstream-kafka-runtime/src/main/java/ai/langstream/kafka/runner/kafkaconnect/KafkaConnectSourceAgent.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunnerStarter.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/CompositeAgentProcessor.java
- langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/metrics/PrometheusMetricsReporter.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/AbstractApplicationRunner.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/GenIAgentsRunnerIT.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/mockagents/MockProcessorAgentsCodeProvider.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/LoadAgentCodeTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/agent/AgentRunnerStarterTest.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/runtime/agent/AgentRunnerTest.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/LocalApplicationRunner.java
Summary:
- add metrics around the source and the sink in each "executor"
- refactor some code in order to reduce code duplication
The new metrics are:
- `source_out`: This is the number of records emitted by the source
- `sink_in`: This is the number of records sent to the sink
> Metrics: add basic metrics about sources and sinks

- mini-langstream/mini-langstream
Add error handling to the shell script function `start_port_forward` to avoid the current hanging if no *node port* is defined for the service.
Doesn't attempt any alternate forwarding (eg kubectl), just gives a moderately helpful message and errors out.
> MiniLangstream should error out if no NodePort exists for a service (#698)

- langstream-cli/src/main/java/ai/langstream/cli/LangStreamCLI.java
Allow specifying the LangStream home directory, via the LANGSTREAM_HOME property (or environment variable).
If not specified, continue to use .langstream in the user's home directory, but allow that to be a symlink. Fixes #697
> LangStream Home from Property, support Symlinks

- helm/crds/applications.langstream.ai-v1.yml
- langstream-admin-client/src/main/java/ai/langstream/admin/client/AdminClient.java
- langstream-admin-client/src/main/java/ai/langstream/admin/client/model/Applications.java
- langstream-api/src/main/java/ai/langstream/api/storage/ApplicationStore.java
- langstream-cli/src/main/java/ai/langstream/cli/commands/applications/DeleteApplicationCmd.java
- langstream-cli/src/test/java/ai/langstream/cli/commands/applications/AppsCmdTest.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/AppLifecycleIT.java
- langstream-e2e-tests/src/test/java/ai/langstream/tests/util/BaseEndToEndTest.java
- langstream-k8s-deployer/langstream-k8s-deployer-api/src/main/java/ai/langstream/deployer/k8s/api/crds/apps/ApplicationSpec.java
- langstream-k8s-deployer/langstream-k8s-deployer-api/src/main/java/ai/langstream/deployer/k8s/api/crds/apps/ApplicationSpecOptions.java
- langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/util/KubeUtil.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/apps/AppController.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/AppControllerIT.java
- langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/OperatorExtension.java
- langstream-k8s-storage/src/main/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStore.java
- langstream-k8s-storage/src/test/java/ai/langstream/impl/storage/k8s/apps/KubernetesApplicationStoreTest.java
- langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/InMemoryApplicationStore.java
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationResource.java
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationService.java
- langstream-webservice/src/main/java/ai/langstream/webservice/common/TenantResource.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/ApplicationResourceTest.java
- langstream-webservice/src/test/java/ai/langstream/webservice/application/ApplicationServiceResourceLimitTest.java
Changes:
* If the deployer/setup job during deploy or deletion fails, we now report the error in the application status
* There's a new option in the deletion `-f`, to skip cleanup errors and go ahead with the application deletion
Implementation:
* There's a new field in the application crd that handles wether the application can skip the cleanup or not in case of failures (only 1 attempt).
* The deletion process totally changes:
* Before: the control plane deletes the app CRD and the finalizer is triggered in the operator. This triggers the cleanup and in case of failures, nothing can be done. 
* Now: the control plane puts a flag "marked for deletion" in the crd specs. In this way it's then possible to force the deletion of the app after the app failed to be deleted. This was not …
> Apps: implement force deletion and improve status

- examples/applications/ollama-chatbot/README.md
- examples/applications/ollama-chatbot/chatbot.yaml
- examples/applications/ollama-chatbot/configuration.yaml
- examples/applications/ollama-chatbot/crawler.yaml
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/embeddings/AbstractHuggingFaceEmbeddingService.java
- langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/embeddings/HuggingFaceEmbeddingService.java
- langstream-agents/langstream-ai-agents/src/test/java/com/datastax/oss/streaming/ai/embeddings/HuggingFaceEmbeddingServiceTest.java
- langstream-core/src/main/java/ai/langstream/impl/nar/NarFileHandler.java
Summary:
when running in docker we use thread to simulate pods and the pipelines share the JVM.
There are some issues with PyTorch/DJL and classloading.
This patch fixes them and moved the Ollame example to using HuggingFace
> [HuggingFace] Make hugging face embeddings work in docker run with multiple pipelines

- examples/applications/chatbot-rag-memory/chatbot.yaml
- examples/applications/chatbot-rag-memory/write-to-astra.yaml
- examples/applications/rag-aws/ingest.yaml
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/vectors/PineconeVectorDatabaseWriterConfig.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/agents/AgentValidationTestUtil.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/agents/QueryVectorDBAgentProviderTest.java
To pass a metadata field in the pinecone vector-db-sink you have to use the syntax `vector.metadata.my-field`. Starting from 0.4.x, this syntax is blocked by the control plane and it should not
> Fix Pinecone config vector.metadata.X

- examples/applications/query-solr/chatbot.yaml
- examples/applications/query-solr/configuration.yaml
- examples/applications/query-solr/crawler.yaml
Summary:
in the Apache Solr sample application use Hugging Face to compute the embeddings, this way the application can run also with an OpenAI account with very low rate limits. 
OpenAI will be used only as LLM
> Solr example: use Hugging face embeddings

- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/grpc_service.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/test_grpc_sink.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/test_grpc_source.py
The iterator method and context read/write APIs can't be mixed.
So this PR changes to use only the context API in read operation.
Also simplifies the tests by using the context API when it's easier than the iterator.
> Fix Python agent read when an error is raised

- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/api.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/grpc_service.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/test_grpc_topic_producer.py
See #649 
After that, remaining work for topic producer will be:
* Support AVRO schema
* Add e2e tests
> Add topic producer API Python side

- langstream-e2e-tests/src/test/java/ai/langstream/tests/PythonAgentsIT.java
- langstream-e2e-tests/src/test/resources/apps/python-processor/gateways.yaml
- langstream-e2e-tests/src/test/resources/apps/python-processor/pipeline.yaml
- langstream-e2e-tests/src/test/resources/apps/python-processor/python/example.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/grpc_service.py
> Add e2e test for topic producer

- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/WebCrawlerSource.java
- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawler.java
- langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerConfiguration.java
- langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerTest.java
- langstream-k8s-runtime/langstream-k8s-runtime-core/src/main/java/ai/langstream/runtime/impl/k8s/agents/WebCrawlerSourceAgentProvider.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/WebCrawlerSourceIT.java
Summary:
- allow users to configure "allow-non-html-contents"
> [webcrawler-source] Expose the allow-non-html-contents parameter

- langstream-agents/langstream-ai-agents/pom.xml
Summary:
- we recently added a dependency (astra-sdk and stargate-sdk) that introduced back an old version of the DataStax Cassandra Driver 4.15.0, that is not compatible with the VECTOR datatype
- we are using the "shaded" version and so Maven kept both the artifacts, the non-shaded 4.15.0 and the shaded 4.16.0
> [cassandra] Remove legacy driver from classpath

- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/AbstractGrpcAgent.java
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/grpc_service.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/server_and_stub.py
- langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/test_grpc_processor.py
Fix #744 
This is the max limit on Java.
> Set gRPC message limit to 2GB

- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/GrpcAgentProcessor.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/GrpcAgentSink.java
- langstream-agents/langstream-agent-grpc/src/main/java/ai/langstream/agents/grpc/GrpcAgentSource.java
This fix uses the asyncStub which was configured to handle 2GB messages with Python agents.
> Fix for handling big messages from Python agent

- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/ConsumeGateway.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/gateways/ProduceGateway.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/http/GatewayResource.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/runner/ClusterRuntimeRegistryBean.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/WebSocketConfig.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/AbstractHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ChatHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ConsumeHandler.java
- langstream-api-gateway/src/main/java/ai/langstream/apigateway/websocket/handlers/ProduceHandler.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/http/GatewayResourceTest.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/http/PulsarTenantGatewayResourceTest.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/websocket/handlers/PulsarContainerExtension.java
- langstream-api-gateway/src/test/java/ai/langstream/apigateway/websocket/handlers/PulsarTenantProduceConsumeHandlerTest.java
- langstream-api/src/main/java/ai/langstream/api/model/Application.java
- langstream-api/src/main/java/ai/langstream/api/runtime/StreamingClusterRuntime.java
- langstream-core/src/main/java/ai/langstream/impl/common/BasicClusterRuntime.java
- langstream-kafka/src/main/java/ai/langstream/kafka/runtime/KafkaStreamingClusterRuntime.java
- langstream-pravega/src/main/java/ai/langstream/pravega/PravegaStreamingClusterRuntime.java
- langstream-pulsar-runtime/src/test/java/ai/langstream/pulsar/PulsarContainerExtension.java
- langstream-pulsar/src/main/java/ai/langstream/pulsar/PulsarStreamingClusterRuntime.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/pravega/PulsarContainerExtension.java
- langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/pravega/PulsarRunnerDockerTest.java
- langstream-runtime/langstream-runtime-tester/pom.xml
- langstream-runtime/langstream-runtime-tester/src/main/docker/Dockerfile
- langstream-webservice/src/main/java/ai/langstream/webservice/application/ApplicationService.java
- Gateway using Pulsar as streaming cluster are not considering the default tenant/namespace defined
> gateway: fix Pulsar topics with non default tenant
