README.md
examples/applications/compute-openai-embeddings/pipeline.yaml

@nicoloboschi and I both made updates to the README. I have merged some of the updates I made in PR#235 with the updates he already made.

Merge readme updates from PR 235

---

.github/workflows/deploy-post-commit.yml
.github/workflows/release.yml
dev/clear-minikube.sh
dev/deploy-minikube.sh
dev/start-local.sh
helm/examples/local.yaml
langstream-api-gateway/pom.xml
langstream-api-gateway/src/main/resources/application.properties
langstream-cli/pom.xml
langstream-cli/src/main/docker/Dockerfile
langstream-e2e-tests/src/test/java/ai/langstream/tests/BaseEndToEndTest.java
langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/resources/application.properties
langstream-k8s-deployer/langstream-k8s-deployer-operator/src/test/java/ai/langstream/deployer/k8s/controllers/OperatorExtension.java
langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/k8s/KubernetesClusterRuntimeDockerTest.java
langstream-runtime/langstream-runtime-impl/pom.xml
langstream-runtime/langstream-runtime-impl/src/main/docker/Dockerfile
langstream-webservice/pom.xml
langstream-webservice/src/main/resources/application.properties

* Release process now pushes to ghcr.io/LangStream/langstream-XX
* Docker images generated locally will be under langstream instead of datastax. e.g. datastax/langstream-runtime -> langstream/langstream-runtime

Move docker images to Github Container Registry

---

README.md

Add CLI autocomplete instructions for Bash

---

langstream-agents/langstream-agents-text-processing/src/main/java/ai/langstream/agents/text/TextNormaliserAgent.java
langstream-agents/langstream-agents-text-processing/src/test/java/ai/langstream/agents/text/TextNormaliserAgentTest.java

Summary:
- remove more spaces and tabs in the text-normaliser agent
- do lowercasing after removing the spaces

Text Normaliser: improvements

---

bin/get-cli.sh

- Change the CLI install script to grap the latest github release while installing the tarball. This also simplify the release process. 
- If `jq` is not installed, the installation fails. It's possible to skip this part by setting the env LANGSTREAM_CLI_URL to a specific url

Cli installation: get latest version by default

---

langstream-agents/langstream-ai-agents/src/test/java/ai/langstream/ai/agents/GenAIToolKitAgentTest.java
pom.xml

Summary:
- include the new functions fn:split, fn:unpack, fn:fromJson, fn:toJson added with 3.1.8

Update DataStax AI functions to 3.1.8

---

langstream-k8s-runtime/langstream-k8s-runtime-core/src/test/java/ai/langstream/runtime/impl/testagents/MockFailingAgentProcessorProvider.java
langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/AgentRunner.java
langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/ErrorHandlingTest.java
langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/FailingProcessorAgentCodeProvider.java

Summary:
- implement on-failure for native Java Sinks

Sinks: handle errors

---

langstream-webservice/src/main/java/ai/langstream/webservice/security/infrastructure/primary/JwksUriSigningKeyResolver.java

Same problem as https://github.com/LangStream/langstream/pull/288 but for another auth stage
GCP enforces the OpenID endpoint to not pass the token. 
Other k8s implementation instead requires the token.
The current strategy is to first try without token and if it fails, retry with the token

Fix OpenID discovery on GCP - part2

---

langstream-cli/src/main/java/ai/langstream/cli/commands/applications/AbstractDeployApplicationCmd.java
langstream-cli/src/test/java/ai/langstream/cli/commands/applications/AppsCmdTest.java

Fix https://github.com/LangStream/langstream/issues/281

Cli: fix apps partial update

---

examples/applications/webcrawler-source/chatbot.yaml
examples/applications/webcrawler-source/crawler.yaml
langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/WebCrawlerSource.java
langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawler.java
langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerConfiguration.java
langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerStatus.java
langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/WebCrawlerSourceTest.java
langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerConfigurationTest.java
langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/mockagents/MockProcessorAgentsCodeProvider.java

Summary:
- add a way to block indexing some paths
- add a way to auto reindex the website after some time
- fix handling of urls with fragment

WebCrawler enhancements: forbidden users and auto-reindex

---

examples/applications/openai-completions/pipeline.yaml
examples/applications/webcrawler-source/README.md
examples/applications/webcrawler-source/chatbot.yaml
examples/applications/webcrawler-source/gateways.yaml
langstream-runtime/langstream-runtime-impl/src/main/java/ai/langstream/runtime/agent/CompositeAgentProcessor.java
langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/ChatCompletionsIT.java

Summary:
- enhance the example applications
- fix a bug in the CompositeAgentProcessor, in order to allow the internal agents to access the AgentContext (to write the streaming response)
- enhance the integration tests

Chat completion: fix the demo apps and make streaming response work with CompositeAgentProcessor

---

langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/agents/AgentResourcesFactory.java
langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/apps/AppResourcesFactory.java
langstream-k8s-deployer/langstream-k8s-deployer-core/src/main/java/ai/langstream/deployer/k8s/util/KubeUtil.java
langstream-k8s-deployer/langstream-k8s-deployer-core/src/test/java/ai/langstream/deployer/k8s/util/KubeUtilTest.java
langstream-k8s-deployer/langstream-k8s-deployer-operator/src/main/java/ai/langstream/deployer/k8s/controllers/apps/AppController.java

Fixes #207
* Handle job completed as a good state
* Set deleting when the cleanup job starts

Fix application status while deploying

---

langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/kafka/KafkaRunnerDockerTest.java

Add a test about Topic retention
```
module: "module-1"
id: "pipeline-1"
topics:
- name: "input-topic-with-retention"
config:
retention.ms: 300000
pipeline:
- id: "step1"
type: "identity"
input: "input-topic-with-retention"
```

Add test about Kafka topic retention

---

langstream-agents/langstream-agents-text-processing/src/main/java/ai/langstream/agents/text/TextNormaliserAgent.java
langstream-agents/langstream-agents-text-processing/src/test/java/ai/langstream/agents/text/TextNormaliserAgentTest.java

Summary:
- more improvements about removing useless sequences
- we still want to keep newlines and double new lines (they may have semantic meaning, like delimiting sections)

TextNormalizer: improvements

---

langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/kafka_connection.py
langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/tests/test_kafka_connection.py

Also changed the headers inferred serializer to mimick Java (the first non-null header type sets the serializer for all subsequent headers).

Replace serializer by one inferred from type if it's ByteArraySerializer

---

examples/applications/langchain-source/python/s3_langchain.py
langstream-runtime/langstream-runtime-impl/src/main/python/Pipfile.lock

Using langchain 0.0.283 that has the improved S3DirectoryLoader

Update langchain example

---

langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/kafka_connection.py

Default Kafka producer serializer to ByteArraySerializer

---

bin/langstream
langstream-admin-client/pom.xml
langstream-cli/pom.xml
langstream-cli/src/main/java/ai/langstream/cli/commands/BaseCmd.java

* There were some conflicts due to pull requests merged at the same time
* we should set *release* in the compiler
* Fix bin/langstream script

Fix cli using jdk11

---

langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/kafka_connection.py
langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/kafka_serialization.py
langstream-runtime/langstream-runtime-impl/src/main/python/langstream_runtime/tests/test_kafka_connection.py

Add support for Kafka UUID Serdes in Python

---

langstream-agents/langstream-agents-text-processing/src/main/java/ai/langstream/agents/text/TikaTextExtractorAgent.java
langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
langstream-runtime/langstream-runtime-tester/pom.xml
langstream-runtime/langstream-runtime-tester/src/main/assemble/entrypoint.sh
langstream-runtime/langstream-runtime-tester/src/main/docker/Dockerfile

Summary:
- make minio work on the docker container
- make the WebCrawler App work in the docker container

[cli] docker run, make Minio work

---

langstream-cli/src/main/java/ai/langstream/cli/commands/docker/LocalRunApplicationCmd.java
langstream-runtime/langstream-runtime-tester/src/main/java/ai/langstream/runtime/tester/Main.java

If you don't pass the secrets there's a NPE in the code

CLI: local run without passing secrets

---

docker/build.sh
langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/embeddings/OpenAIEmbeddingsService.java
langstream-agents/langstream-ai-agents/src/main/java/com/datastax/oss/streaming/ai/util/TransformFunctionUtil.java
langstream-runtime/langstream-runtime-tester/pom.xml
langstream-runtime/langstream-runtime-tester/src/main/assemble/entrypoint.sh
langstream-runtime/langstream-runtime-tester/src/main/assemble/langstream-runtime-tester.xml
langstream-runtime/langstream-runtime-tester/src/main/assemble/logback.xml
langstream-runtime/langstream-runtime-tester/src/main/docker/Dockerfile

Move to the OpenAI Async client

---

.github/workflows/ci.yml

to reduce the amount of logs in CI

Do not display transfer progress during CI

---

examples/applications/query-milvus/crawler.yaml
langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/InterpolationUtils.java
langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/milvus/MilvusAssetsManagerProvider.java
langstream-agents/langstream-vector-agents/src/main/java/ai/langstream/agents/vector/milvus/MilvusModel.java
langstream-agents/langstream-vector-agents/src/test/java/ai/langstream/agents/vector/datasource/impl/MilvusDataSourceTest.java

Summary:
- added "create-index" command
- modified the sample application

[milvus] Implement create-index command

---

examples/applications/docker-chatbot/README.md

Preview here:
https://github.com/LangStream/langstream/tree/example-chart/examples/applications/docker-chatbot#application-flow-chart

Add chart to docker-chatbot example

---

langstream-kafka-runtime/src/main/java/ai/langstream/kafka/runner/KafkaProducerWrapper.java
langstream-kafka-runtime/src/test/java/ai/langstream/kafka/KafkaConsumerTest.java

Kafka: add serializer for raw Maps and Lists

---

examples/applications/docker-chatbot/chatbot.yaml
examples/applications/query-milvus/chatbot.yaml
examples/applications/webcrawler-source/chatbot.yaml
langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerConfiguration.java
langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/crawler/WebCrawlerConfigurationTest.java

[webcrawler] Fix NPE in case of wrong URLs without slashes

---

langstream-cli/src/main/resources/app-ui/index.html

* Fixed html code as response to be rendered
* Added new checkbox (not checked) to render the text as HTML (only for new messages)

App UI: escape HTML and render markdown (optional)

---

examples/applications/react-chatbot-ui/src/Chatbot/LoadingMessage.tsx
examples/applications/react-chatbot-ui/src/Chatbot/Message.tsx
examples/applications/react-chatbot-ui/src/Chatbot/index.tsx
examples/applications/react-chatbot-ui/src/hooks/useWebSocket.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX11a3J2hR1REDOuPT7hZnkS3vi9SZdSI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Q4Yzhdq)
Loading State: 
Now w/ full width responses:

React-Chatbot-UI: Add Loading state and style updates

---

langstream-pulsar-runtime/src/main/java/ai/langstream/pulsar/runner/PulsarTopicConnectionsRuntimeProvider.java
langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/grpc_service.py
langstream-runtime/langstream-runtime-impl/src/test/java/ai/langstream/pulsar/PulsarRunnerDockerTest.java

Add suport for KeyValue in Pulsar

---

langstream-cli/src/main/java/ai/langstream/cli/commands/applications/UIAppCmd.java

using localhost or 127.0.0.1 doest work in WSL Ubuntu

Update UIAppCmd.java to set UI on 0.0.0.0

---

langstream-agents/langstream-agent-webcrawler/src/main/java/ai/langstream/agents/webcrawler/crawler/WebCrawler.java
langstream-agents/langstream-agent-webcrawler/src/test/java/ai/langstream/agents/webcrawler/WebCrawlerSourceTest.java

Fixes #678 
Summary:
- handle errors while parsing sitemaps
- allow to skip sitemaps with "forbidden paths"

[webcrawler] Handle bad sitemaps and allow to skip them

---

examples/applications/docker-chatbot/chatbot.yaml
examples/applications/docker-chatbot/crawler.yaml
examples/applications/ollama-chatbot/README.md
examples/applications/ollama-chatbot/chatbot.yaml
examples/applications/ollama-chatbot/configuration.yaml
examples/applications/ollama-chatbot/crawler.yaml
examples/secrets/secrets.yaml

Summary:
- use OpenAI Embeddings, they perform better
- switch to llama2:13b
- make the prompt more effective for the  llama2:13b model

[examples] Finalise the Ollama example application

---

examples/applications/azure-document-ingestion/README.md

Docs only change. 
Added pipeline UI screenshot.

[docs] Improved readme by adding an important screenshot and description

---

langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/grpc_service.py
langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/test_grpc_processor.py
langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/test_grpc_sink.py
langstream-runtime/langstream-runtime-impl/src/main/python/langstream_grpc/tests/test_grpc_source.py

Will make it easier to use TopicProducer::write as it will return async.

Add support for async functions in agents
